// Flashcard themes — sourced from "De Opmaat" (Beersmans & Tersteeg, 2020).
// Each card has a stable id derived from theme + Dutch slug so user progress
// survives edits to this file. Add new themes here.
import { VERB_THEMES } from './verbs.js';
import { SENTENCE_THEMES } from './sentences.js';

export const THEMES = [
  {
    id: 't1',
    name: 'Kennismaken',
    label: "Theme 1 · Kennismaken en afspreken (Introductions)",
    cards: [
      { nl: 'achternaam', article: 'de', en: 'surname / last name' },
      { nl: 'adres', article: 'het', en: 'address' },
      { nl: 'afspreken', en: 'to make an appointment / agree' },
      { nl: 'agenda', article: 'de', en: 'planner / agenda' },
      { nl: 'al', en: 'already' },
      { nl: 'als', en: 'if / when / as' },
      { nl: 'antwoord', article: 'het', en: 'answer' },
      { nl: 'apotheker', article: 'de', en: 'pharmacist' },
      { nl: 'april', en: 'April' },
      { nl: 'arts', article: 'de', en: 'doctor' },
      { nl: 'augustus', en: 'August' },
      { nl: 'auto', article: 'de', en: 'car' },
      { nl: 'avond', article: 'de', en: 'evening' },
      { nl: 'banaan', article: 'de', en: 'banana' },
      { nl: 'bank', article: 'de', en: 'sofa / bank' },
      { nl: 'beamer', article: 'de', en: 'projector' },
      { nl: 'beantwoorden', en: 'to answer' },
      { nl: 'beetje', en: 'a little bit' },
      { nl: 'beginnen', en: 'to begin' },
      { nl: 'beker', article: 'de', en: 'cup / mug / beaker' },
      { nl: 'beroep', article: 'het', en: 'profession' },
      { nl: 'bibliotheek', article: 'de', en: 'library' },
      { nl: 'bier', article: 'het', en: 'beer' },
      { nl: 'bij', en: 'at / with / near' },
      { nl: 'biologisch', en: 'organic / biological' },
      { nl: 'bioscoop', article: 'de', en: 'cinema' },
      { nl: 'blijven', en: 'to stay / remain' },
      { nl: 'boek', article: 'het', en: 'book' },
      { nl: 'bord', article: 'het', en: 'plate / sign' },
      { nl: 'café', article: 'het', en: 'café' },
      { nl: 'cd-speler', article: 'de', en: 'CD player' },
      { nl: 'computer', article: 'de', en: 'computer' },
      { nl: 'concert', article: 'het', en: 'concert' },
      { nl: 'cursist', article: 'de', en: 'course participant' },
      { nl: 'cursus', article: 'de', en: 'course' },
      { nl: 'cursusboek', article: 'het', en: 'course book' },
      { nl: 'daar', en: 'there' },
      { nl: 'dag', article: 'de', en: 'day' },
      { nl: 'dan', en: 'then' },
      { nl: 'dank', en: 'thanks' },
      { nl: 'dansclub', article: 'de', en: 'dance club' },
      { nl: 'dansen', en: 'to dance' },
      { nl: 'de', en: 'the (common gender)' },
      { nl: 'december', en: 'December' },
      { nl: 'denken', en: 'to think' },
      { nl: 'deur', article: 'de', en: 'door' },
      { nl: 'deze', en: 'this / these' },
      { nl: 'dier', article: 'het', en: 'animal' },
      { nl: 'dierentuin', article: 'de', en: 'zoo' },
      { nl: 'dinsdag', en: 'Tuesday' },
      { nl: 'docent', article: 'de', en: 'teacher / lecturer' },
      { nl: 'doen', en: 'to do' },
      { nl: 'donderdag', en: 'Thursday' },
      { nl: 'dorp', article: 'het', en: 'village' },
      { nl: 'drinken', en: 'to drink' },
      { nl: 'dubbel', en: 'double' },
      { nl: 'economie', article: 'de', en: 'economy / economics' },
      { nl: 'een', en: 'a / one' },
      { nl: 'eergisteren', en: 'the day before yesterday' },
      { nl: 'ei', article: 'het', en: 'egg' },
      { nl: 'elke', en: 'every / each' },
      { nl: 'en', en: 'and' },
      { nl: 'Engels', article: 'het', en: 'English (language)' },
      { nl: 'eten', en: 'to eat / food' },
      { nl: 'expositie', article: 'de', en: 'exhibition' },
      { nl: 'februari', en: 'February' },
      { nl: 'film', article: 'de', en: 'film / movie' },
      { nl: 'fruit', article: 'het', en: 'fruit' },
      { nl: 'gaan', en: 'to go' },
      { nl: 'getal', article: 'het', en: 'number (numeric)' },
      { nl: 'gisteravond', en: 'last night' },
      { nl: 'gisteren', en: 'yesterday' },
      { nl: 'geboortedatum', article: 'de', en: 'date of birth' },
      { nl: 'geboren', en: 'born' },
      { nl: 'geld', article: 'het', en: 'money' },
      { nl: 'geleden', en: 'ago' },
      { nl: 'glas', article: 'het', en: 'glass' },
      { nl: 'goed', en: 'good' },
      { nl: 'goedemiddag', en: 'good afternoon' },
      { nl: 'goedemorgen', en: 'good morning' },
      { nl: 'goedenacht', en: 'goodnight' },
      { nl: 'goedenavond', en: 'good evening' },
      { nl: 'goedendag', en: 'good day / hello' },
      { nl: 'goh', en: 'oh / wow (interjection)' },
      { nl: 'groep', article: 'de', en: 'group' },
      { nl: 'gum', article: 'de', en: 'eraser' },
      { nl: 'half', en: 'half' },
      { nl: 'hallo', en: 'hello' },
      { nl: 'hard', en: 'hard / loud / fast' },
      { nl: 'hè', en: 'eh / huh' },
      { nl: 'hebben', en: 'to have' },
      { nl: 'het', en: 'the (neuter) / it' },
      { nl: 'heten', en: 'to be called' },
      { nl: 'hier', en: 'here' },
      { nl: 'hij', en: 'he' },
      { nl: 'hoe', en: 'how' },
      { nl: 'hoi', en: 'hi' },
      { nl: 'huis', article: 'het', en: 'house' },
      { nl: 'huiswerk', article: 'het', en: 'homework' },
      { nl: 'iets', en: 'something' },
      { nl: 'ijs', article: 'het', en: 'ice / ice cream' },
      { nl: 'ik', en: 'I' },
      { nl: 'in', en: 'in' },
      { nl: 'ja', en: 'yes' },
      { nl: 'jaar', article: 'het', en: 'year' },
      { nl: 'januari', en: 'January' },
      { nl: 'jas', article: 'de', en: 'coat / jacket' },
      { nl: 'je / jij', en: 'you (informal)' },
      { nl: 'juli', en: 'July' },
      { nl: 'jullie', en: 'you (plural)' },
      { nl: 'juni', en: 'June' },
      { nl: 'kapstok', article: 'de', en: 'coat rack' },
      { nl: 'kennen', en: 'to know (be acquainted)' },
      { nl: 'kerk', article: 'de', en: 'church' },
      { nl: 'klok', article: 'de', en: 'clock' },
      { nl: 'koffie', article: 'de', en: 'coffee' },
      { nl: 'komen', en: 'to come' },
      { nl: 'kopen', en: 'to buy' },
      { nl: 'kopje', article: 'het', en: 'cup (small)' },
      { nl: 'laat', en: 'late' },
      { nl: 'lamp', article: 'de', en: 'lamp' },
      { nl: 'land', article: 'het', en: 'country' },
      { nl: 'landkaart', article: 'de', en: 'map (of a country)' },
      { nl: 'leeftijd', article: 'de', en: 'age' },
      { nl: 'lenen', en: 'to borrow / lend' },
      { nl: 'les', article: 'de', en: 'lesson' },
      { nl: 'letter', article: 'de', en: 'letter (of alphabet)' },
      { nl: 'leven', en: 'to live / life' },
      { nl: 'lezen', en: 'to read' },
      { nl: 'liggen', en: 'to lie / be located' },
      { nl: 'lunchen', en: 'to have lunch' },
      { nl: 'luisteren', en: 'to listen' },
      { nl: 'maand', article: 'de', en: 'month' },
      { nl: 'maandag', en: 'Monday' },
      { nl: 'maart', en: 'March' },
      { nl: 'map', article: 'de', en: 'folder' },
      { nl: 'markt', article: 'de', en: 'market' },
      { nl: 'medicijn', article: 'de/het', en: 'medicine' },
      { nl: 'meestal', en: 'usually / most often' },
      { nl: 'mei', en: 'May' },
      { nl: 'met', en: 'with' },
      { nl: 'middag', article: 'de', en: 'afternoon' },
      { nl: 'mild', en: 'mild' },
      { nl: 'mijn', en: 'my' },
      { nl: 'miljoen', article: 'het', en: 'million' },
      { nl: 'morgen', en: 'tomorrow / morning' },
      { nl: 'museum', article: 'het', en: 'museum' },
      { nl: 'muur', article: 'de', en: 'wall' },
      { nl: 'muziek', article: 'de', en: 'music' },
      { nl: 'muziekcentrum', article: 'het', en: 'music centre' },
      { nl: 'naam', article: 'de', en: 'name' },
      { nl: 'naar', en: 'to / towards' },
      { nl: 'nacht', article: 'de', en: 'night' },
      { nl: 'nationaliteit', article: 'de', en: 'nationality' },
      { nl: 'Nederland', en: 'the Netherlands' },
      { nl: 'Nederlander', article: 'de', en: 'Dutch person' },
      { nl: 'Nederlands', article: 'het', en: 'Dutch (language)' },
      { nl: 'nee', en: 'no' },
      { nl: 'niet', en: 'not' },
      { nl: 'november', en: 'November' },
      { nl: 'nu', en: 'now' },
      { nl: 'nummer', article: 'het', en: 'number' },
      { nl: 'ochtend', article: 'de', en: 'morning' },
      { nl: 'oktober', en: 'October' },
      { nl: 'om', en: 'at (time) / around' },
      { nl: 'ontmoeten', en: 'to meet' },
      { nl: 'oud', en: 'old' },
      { nl: 'overmorgen', en: 'the day after tomorrow' },
      { nl: 'pakken', en: 'to grab / take' },
      { nl: 'papier', article: 'het', en: 'paper' },
      { nl: 'park', article: 'het', en: 'park' },
      { nl: 'pen', article: 'de', en: 'pen' },
      { nl: 'pittig', en: 'spicy' },
      { nl: 'plaats', article: 'de', en: 'place / seat' },
      { nl: 'plafond', article: 'het', en: 'ceiling' },
      { nl: 'postcode', article: 'de', en: 'postal code' },
      { nl: 'postkantoor', article: 'het', en: 'post office' },
      { nl: 'postzegel', article: 'de', en: 'postage stamp' },
      { nl: 'potlood', article: 'het', en: 'pencil' },
      { nl: 'prikbord', article: 'het', en: 'notice board' },
      { nl: 'prima', en: 'fine / great' },
      { nl: 'psychologie', article: 'de', en: 'psychology' },
      { nl: 'raam', article: 'het', en: 'window' },
      { nl: 'redelijk', en: 'reasonable / reasonably' },
      { nl: 'reizen', en: 'to travel' },
      { nl: 'restaurant', article: 'het', en: 'restaurant' },
      { nl: 'schrift', article: 'het', en: 'notebook' },
      { nl: 'schrijven', en: 'to write' },
      { nl: 'september', en: 'September' },
      { nl: 'slecht', en: 'bad' },
      { nl: 'soms', en: 'sometimes' },
      { nl: 'sorry', en: 'sorry' },
      { nl: 'Spaans', article: 'het', en: 'Spanish (language)' },
      { nl: 'sporten', en: 'to do sports' },
      { nl: 'sporthal', article: 'de', en: 'sports hall' },
      { nl: 'spreken', en: 'to speak' },
      { nl: 'stad', article: 'de', en: 'city' },
      { nl: 'stage', article: 'de', en: 'internship' },
      { nl: 'station', article: 'het', en: 'station' },
      { nl: 'stift', article: 'de', en: 'marker / felt-tip' },
      { nl: 'stoel', article: 'de', en: 'chair' },
      { nl: 'stoppen', en: 'to stop' },
      { nl: 'straat', article: 'de', en: 'street' },
      { nl: 'strand', article: 'het', en: 'beach' },
      { nl: 'student', article: 'de', en: 'student' },
      { nl: 'studeren', en: 'to study' },
      { nl: 'studie', article: 'de', en: 'studies' },
      { nl: 'taal', article: 'de', en: 'language' },
      { nl: 'taalinstituut', article: 'het', en: 'language institute' },
      { nl: 'tafel', article: 'de', en: 'table' },
      { nl: 'tas', article: 'de', en: 'bag' },
      { nl: 'tekst', article: 'de', en: 'text' },
      { nl: 'telefoonnummer', article: 'het', en: 'phone number' },
      { nl: 'televisie', article: 'de', en: 'television' },
      { nl: 'tennisbaan', article: 'de', en: 'tennis court' },
      { nl: 'tennissen', en: 'to play tennis' },
      { nl: 'theater', article: 'het', en: 'theatre' },
      { nl: 'thee', article: 'de', en: 'tea' },
      { nl: 'tot', en: 'until / to' },
      { nl: 'trein', article: 'de', en: 'train' },
      { nl: 'u', en: 'you (formal)' },
      { nl: 'uit', en: 'from / out of' },
      { nl: 'universiteit', article: 'de', en: 'university' },
      { nl: 'vanavond', en: 'tonight / this evening' },
      { nl: 'vandaag', en: 'today' },
      { nl: 'vandaan', en: 'from (where … from)' },
      { nl: 'vanmiddag', en: 'this afternoon' },
      { nl: 'vanmorgen', en: 'this morning' },
      { nl: 'vannacht', en: 'tonight (late) / last night' },
      { nl: 'vinden', en: 'to find / think' },
      { nl: 'vloer', article: 'de', en: 'floor' },
      { nl: 'voorbeeld', article: 'het', en: 'example' },
      { nl: 'voornaam', article: 'de', en: 'first name' },
      { nl: 'vraag', article: 'de', en: 'question' },
      { nl: 'vriend', article: 'de', en: 'friend (m) / boyfriend' },
      { nl: 'vriendin', article: 'de', en: 'friend (f) / girlfriend' },
      { nl: 'vrij', en: 'free' },
      { nl: 'vrijdag', en: 'Friday' },
      { nl: 'waar', en: 'where / true' },
      { nl: 'wandelen', en: 'to walk / hike' },
      { nl: 'wanneer', en: 'when' },
      { nl: 'wat', en: 'what / something' },
      { nl: 'we', en: 'we' },
      { nl: 'week', article: 'de', en: 'week' },
      { nl: 'welk(e)', en: 'which' },
      { nl: 'werken', en: 'to work' },
      { nl: 'wie', en: 'who' },
      { nl: 'wij', en: 'we' },
      { nl: 'winkelcentrum', article: 'het', en: 'shopping centre' },
      { nl: 'winkelen', en: 'to shop' },
      { nl: 'woensdag', en: 'Wednesday' },
      { nl: 'wonen', en: 'to live (reside)' },
      { nl: 'woord', article: 'het', en: 'word' },
      { nl: 'woordenboek', article: 'het', en: 'dictionary' },
      { nl: 'zaterdag', en: 'Saturday' },
      { nl: 'ze', en: 'she / they' },
      { nl: 'zeggen', en: 'to say' },
      { nl: 'zien', en: 'to see' },
      { nl: 'zij', en: 'she / they' },
      { nl: 'zijn', en: 'to be / his' },
      { nl: 'zitten', en: 'to sit' },
      { nl: 'zon', article: 'de', en: 'sun' },
      { nl: 'zondag', en: 'Sunday' },
      { nl: 'zout', en: 'salt / salty' },
      { nl: 'zwembad', article: 'het', en: 'swimming pool' },
      { nl: 'zwemmen', en: 'to swim' },
    ],
  },
  {
    id: 't2',
    name: 'Feesten',
    label: 'Theme 2 · Feesten (Celebrations)',
    cards: [
      { nl: 'afspraak', article: 'de', en: 'appointment' },
      { nl: 'alcohol', article: 'de', en: 'alcohol' },
      { nl: 'allebei', en: 'both' },
      { nl: 'alleen', en: 'alone / only' },
      { nl: 'alsjeblieft / alstublieft', en: 'please / here you are' },
      { nl: 'appel', article: 'de', en: 'apple' },
      { nl: 'baan', article: 'de', en: 'job' },
      { nl: 'baby', article: 'de', en: 'baby' },
      { nl: 'belangrijk', en: 'important' },
      { nl: 'bespreken', en: 'to discuss' },
      { nl: 'beste', en: 'best / dear' },
      { nl: 'beterschap!', en: 'get well soon!' },
      { nl: 'Bevrijdingsdag', en: 'Liberation Day (May 5)' },
      { nl: 'bezem', article: 'de', en: 'broom' },
      { nl: 'blij', en: 'happy / glad' },
      { nl: 'boekwinkel', article: 'de', en: 'bookshop' },
      { nl: 'bon', article: 'de', en: 'receipt / voucher' },
      { nl: 'bonnetje', article: 'het', en: 'receipt (small)' },
      { nl: 'broer', article: 'de', en: 'brother' },
      { nl: 'cadeautje', article: 'het', en: 'little gift' },
      { nl: 'carnaval', en: 'carnival' },
      { nl: 'contact', article: 'het', en: 'contact' },
      { nl: 'crèche', article: 'de', en: 'daycare / nursery' },
      { nl: 'dansen', en: 'to dance' },
      { nl: 'dat', en: 'that' },
      { nl: 'dicht', en: 'closed' },
      { nl: 'dierendag', en: 'Animal Day (Oct 4)' },
      { nl: 'dit', en: 'this' },
      { nl: 'dochter', article: 'de', en: 'daughter' },
      { nl: 'dodenherdenking', en: 'Remembrance of the Dead (May 4)' },
      { nl: 'echtpaar', article: 'het', en: 'married couple' },
      { nl: 'eindexamen', article: 'het', en: 'final exam' },
      { nl: 'elkaar', en: 'each other' },
      { nl: 'erg', en: 'very / awful' },
      { nl: 'examen', article: 'het', en: 'exam' },
      { nl: 'familie', article: 'de', en: 'family (extended)' },
      { nl: 'feest', article: 'het', en: 'party / celebration' },
      { nl: 'feestdag', article: 'de', en: 'public holiday' },
      { nl: 'feestje', article: 'het', en: 'little party' },
      { nl: 'fiets', article: 'de', en: 'bicycle' },
      { nl: 'fles', article: 'de', en: 'bottle' },
      { nl: 'formulier', article: 'het', en: 'form' },
      { nl: 'foto', article: 'de', en: 'photo' },
      { nl: 'fotograaf', article: 'de', en: 'photographer' },
      { nl: 'gast', article: 'de', en: 'guest' },
      { nl: 'geboorte', article: 'de', en: 'birth' },
      { nl: 'gebruiken', en: 'to use' },
      { nl: 'gecondoleerd', en: 'my condolences' },
      { nl: 'geen', en: 'no / none' },
      { nl: 'gefeliciteerd', en: 'congratulations' },
      { nl: 'gek', en: 'crazy' },
      { nl: 'geleden', en: 'ago' },
      { nl: 'geluk', article: 'het', en: 'luck / happiness' },
      { nl: 'gelukkig', en: 'happy / fortunately' },
      { nl: 'gemeentehuis', article: 'het', en: 'town hall' },
      { nl: 'gescheiden', en: 'divorced' },
      { nl: 'getrouwd', en: 'married' },
      { nl: 'geven', en: 'to give' },
      { nl: 'gezellig', en: 'cozy / sociable' },
      { nl: 'gezin', article: 'het', en: 'family (household)' },
      { nl: 'Goede Vrijdag', en: 'Good Friday' },
      { nl: 'graag', en: 'gladly / please' },
      { nl: 'gracht', article: 'de', en: 'canal' },
      { nl: 'groet', article: 'de', en: 'greeting' },
      { nl: 'groot', en: 'big / large' },
      { nl: 'grootmoeder', article: 'de', en: 'grandmother' },
      { nl: 'grootvader', article: 'de', en: 'grandfather' },
      { nl: 'haar', en: 'her / hair' },
      { nl: 'harte', en: 'heart (as in "van harte")' },
      { nl: 'hartelijk gefeliciteerd', en: 'heartfelt congratulations' },
      { nl: 'Hemelvaart', en: 'Ascension Day' },
      { nl: 'hoeveel', en: 'how much / how many' },
      { nl: 'hoor', en: '(filler) you know / really' },
      { nl: 'horen', en: 'to hear' },
      { nl: 'hond', article: 'de', en: 'dog' },
      { nl: 'houden van', en: 'to love / to like' },
      { nl: 'hun', en: 'their / them' },
      { nl: 'huwelijk', article: 'het', en: 'marriage / wedding' },
      { nl: 'iedereen', en: 'everyone' },
      { nl: 'internationaal', en: 'international' },
      { nl: 'invullen', en: 'to fill in' },
      { nl: 'jarig', en: 'having a birthday' },
      { nl: 'je', en: 'you (informal)' },
      { nl: 'jongen', article: 'de', en: 'boy' },
      { nl: 'jouw', en: 'your (informal)' },
      { nl: 'kamer', article: 'de', en: 'room' },
      { nl: 'kantine', article: 'de', en: 'canteen' },
      { nl: 'kat', article: 'de', en: 'cat' },
      { nl: 'Kerstmis', en: 'Christmas' },
      { nl: 'kind', article: 'het', en: 'child' },
      { nl: 'klaar', en: 'ready / finished' },
      { nl: 'klein', en: 'small' },
      { nl: 'kleindochter', article: 'de', en: 'granddaughter' },
      { nl: 'kleinkind', article: 'het', en: 'grandchild' },
      { nl: 'kleinzoon', article: 'de', en: 'grandson' },
      { nl: 'koffie', article: 'de', en: 'coffee' },
      { nl: 'Koningsdag', en: "King's Day (April 27)" },
      { nl: 'kop', article: 'de', en: 'cup / head' },
      { nl: 'kopen', en: 'to buy' },
      { nl: 'kopje', article: 'het', en: 'small cup' },
      { nl: 'kort', en: 'short' },
      { nl: 'krijgen', en: 'to receive / get' },
      { nl: 'kruispunt', article: 'het', en: 'crossroads' },
      { nl: 'kunnen', en: 'to be able to' },
      { nl: 'lekker', en: 'tasty / nice' },
      { nl: 'lepel', article: 'de', en: 'spoon' },
      { nl: 'leuk', en: 'nice / fun' },
      { nl: 'lijken op', en: 'to look like / resemble' },
      { nl: 'lokaal', article: 'het', en: 'classroom' },
      { nl: 'maar', en: 'but / only' },
      { nl: 'maken', en: 'to make' },
      { nl: 'man', article: 'de', en: 'man / husband' },
      { nl: 'me', en: 'me' },
      { nl: 'mes', article: 'het', en: 'knife' },
      { nl: 'mij', en: 'me' },
      { nl: 'missen', en: 'to miss' },
      { nl: 'moeder', article: 'de', en: 'mother' },
      { nl: 'moederdag', en: "Mother's Day" },
      { nl: 'moeten', en: 'to have to / must' },
      { nl: 'mogen', en: 'to be allowed to / may' },
      { nl: 'muziek', article: 'de', en: 'music' },
      { nl: 'nationaal', en: 'national' },
      { nl: 'neef', article: 'de', en: 'cousin (m) / nephew' },
      { nl: 'neefje', article: 'het', en: 'little nephew' },
      { nl: 'nemen', en: 'to take' },
      { nl: 'nicht', article: 'de', en: 'cousin (f) / niece' },
      { nl: 'nichtje', article: 'het', en: 'little niece' },
      { nl: 'niets', en: 'nothing' },
      { nl: 'nieuw', en: 'new' },
      { nl: 'Nieuwjaar', en: 'New Year' },
      { nl: 'niks', en: 'nothing (informal)' },
      { nl: 'nog', en: 'still / yet' },
      { nl: 'oma', article: 'de', en: 'grandma' },
      { nl: 'onderzoek', article: 'het', en: 'research / examination' },
      { nl: 'ons / onze', en: 'our' },
      { nl: 'oom', article: 'de', en: 'uncle' },
      { nl: 'opa', article: 'de', en: 'grandpa' },
      { nl: 'Oudejaarsavond', en: "New Year's Eve" },
      { nl: 'ouder', article: 'de', en: 'parent' },
      { nl: 'overgrootmoeder', article: 'de', en: 'great-grandmother' },
      { nl: 'overgrootvader', article: 'de', en: 'great-grandfather' },
      { nl: 'overleden', en: 'deceased' },
      { nl: 'paraplu', article: 'de', en: 'umbrella' },
      { nl: 'parfum', article: 'de/het', en: 'perfume' },
      { nl: 'parkeren', en: 'to park' },
      { nl: 'Pasen', en: 'Easter' },
      { nl: 'pauze', en: 'break / pause' },
      { nl: 'persoon', article: 'de', en: 'person' },
      { nl: 'Pinksteren', en: 'Pentecost / Whitsun' },
      { nl: 'plezier', article: 'het', en: 'pleasure / fun' },
      { nl: 'populair', en: 'popular' },
      { nl: 'Prinsjesdag', en: 'Budget Day (Dutch state opening)' },
      { nl: 'proficiat!', en: 'congratulations!' },
      { nl: 'proost!', en: 'cheers!' },
      { nl: 'reageren', en: 'to react / respond' },
      { nl: 'rechtsaf', en: 'to the right' },
      { nl: 'receptie', article: 'de', en: 'reception' },
      { nl: 'roken', en: 'to smoke' },
      { nl: 'ruilen', en: 'to exchange / swap' },
      { nl: 'schoonmoeder', article: 'de', en: 'mother-in-law' },
      { nl: 'schoonouder', article: 'de', en: 'parent-in-law' },
      { nl: 'schoonvader', article: 'de', en: 'father-in-law' },
      { nl: 'schoonzus', article: 'de', en: 'sister-in-law' },
      { nl: 'Sint Maarten', en: "Saint Martin's Day (Nov 11)" },
      { nl: 'Sinterklaas', en: 'Saint Nicholas (Dec 5)' },
      { nl: 'smakelijk', en: 'enjoy your meal' },
      { nl: 'snel', en: 'fast / quickly' },
      { nl: 'staan', en: 'to stand' },
      { nl: 'stellen (vragen stellen)', en: 'to ask (questions)' },
      { nl: 'sterkte!', en: 'strength / take care!' },
      { nl: 'stiefbroer', article: 'de', en: 'stepbrother' },
      { nl: 'stiefmoeder', article: 'de', en: 'stepmother' },
      { nl: 'stiefvader', article: 'de', en: 'stepfather' },
      { nl: 'stiefzus', article: 'de', en: 'stepsister' },
      { nl: 'stuk', article: 'het', en: 'piece' },
      { nl: 'stukje', article: 'het', en: 'small piece' },
      { nl: 'sturen', en: 'to send' },
      { nl: 'succes!', en: 'good luck!' },
      { nl: 'taart', article: 'de', en: 'cake / tart' },
      { nl: 'tandarts', article: 'de', en: 'dentist' },
      { nl: 'tante', article: 'de', en: 'aunt' },
      { nl: 'taxi', article: 'de', en: 'taxi' },
      { nl: 'tegenwoordig', en: 'nowadays' },
      { nl: 'thuis', en: 'at home' },
      { nl: 'tijd', article: 'de', en: 'time' },
      { nl: 'titel', article: 'de', en: 'title' },
      { nl: 'traditie', article: 'de', en: 'tradition' },
      { nl: 'trakteren', en: 'to treat (someone)' },
      { nl: 'trouwen', en: 'to marry / get married' },
      { nl: 'tweeling', article: 'de', en: 'twins' },
      { nl: 'uitnodiging', article: 'de', en: 'invitation' },
      { nl: 'uitspraak', article: 'de', en: 'pronunciation' },
      { nl: 'uw', en: 'your (formal)' },
      { nl: 'vader', article: 'de', en: 'father' },
      { nl: 'Vaderdag', en: "Father's Day" },
      { nl: 'Valentijnsdag', en: "Valentine's Day" },
      { nl: 'van', en: 'from / of' },
      { nl: 'vanaf', en: 'from (starting from)' },
      { nl: 'van harte beterschap!', en: 'heartfelt get well soon!' },
      { nl: 'van harte!', en: 'heartfelt (congrats)!' },
      { nl: 'veel', en: 'much / many' },
      { nl: 'veel plezier!', en: 'have fun!' },
      { nl: 'velen', en: 'many (people)' },
      { nl: 'vergeten', en: 'to forget' },
      { nl: 'verjaardag', article: 'de', en: 'birthday' },
      { nl: 'verhuizen', en: 'to move (house)' },
      { nl: 'verschil', article: 'het', en: 'difference' },
      { nl: 'verstaan', en: 'to understand (auditorily)' },
      { nl: 'vervelend', en: 'annoying / unpleasant' },
      { nl: 'vinden', en: 'to find / think' },
      { nl: 'volgende', en: 'next' },
      { nl: 'volgorde', en: 'order / sequence' },
      { nl: 'voor', en: 'for / in front of' },
      { nl: 'vork', article: 'de', en: 'fork' },
      { nl: 'vrouw', article: 'de', en: 'woman / wife' },
      { nl: 'waarom', en: 'why' },
      { nl: 'wat erg!', en: 'how awful!' },
      { nl: 'wat gezellig!', en: 'how nice!' },
      { nl: 'wat leuk!', en: 'how fun!' },
      { nl: 'Wat', en: 'What' },
      { nl: 'wc', article: 'de', en: 'toilet (WC)' },
      { nl: 'werk', article: 'het', en: 'work' },
      { nl: 'wens', article: 'de', en: 'wish' },
      { nl: 'wijn', article: 'de', en: 'wine' },
      { nl: 'willen', en: 'to want' },
      { nl: 'woning', article: 'de', en: 'dwelling / house' },
      { nl: 'worden', en: 'to become' },
      { nl: 'zet hem op!', en: 'go for it!' },
      { nl: 'ziek', en: 'sick / ill' },
      { nl: 'ziekenhuis', article: 'het', en: 'hospital' },
      { nl: 'zoeken', en: 'to search / look for' },
      { nl: 'zoon', article: 'de', en: 'son' },
      { nl: 'zullen', en: 'shall / will' },
      { nl: 'zus', article: 'de', en: 'sister' },
      { nl: 'zwager', article: 'de', en: 'brother-in-law' },
    ],
  },
  {
    id: 't3',
    name: 'Boodschappen',
    label: 'Theme 3 · Boodschappen doen en winkelen (Shopping)',
    cards: [
      { nl: 'aan', en: 'on / to' },
      { nl: 'aanbieding', article: 'de', en: 'special offer' },
      { nl: 'aantrekken', en: 'to put on (clothes)' },
      { nl: 'aardappel', article: 'de', en: 'potato' },
      { nl: 'aardbei', article: 'de', en: 'strawberry' },
      { nl: 'afrekenen', en: 'to pay / settle the bill' },
      { nl: 'alles', en: 'everything' },
      { nl: 'ananas', article: 'de', en: 'pineapple' },
      { nl: 'anderhalf', en: 'one and a half' },
      { nl: 'anders', en: 'different / otherwise' },
      { nl: 'andijvie', article: 'de', en: 'endive' },
      { nl: 'appel', article: 'de', en: 'apple' },
      { nl: 'armband', article: 'de', en: 'bracelet' },
      { nl: 'aspirine', article: 'de', en: 'aspirin' },
      { nl: 'bakker', article: 'de', en: 'baker' },
      { nl: 'bakkerij', article: 'de', en: 'bakery' },
      { nl: 'bank', article: 'de', en: 'sofa / bank' },
      { nl: 'beige', en: 'beige' },
      { nl: 'bestellen', en: 'to order' },
      { nl: 'betalen', en: 'to pay' },
      { nl: 'beurt', article: 'de', en: 'turn' },
      { nl: 'bh', article: 'de', en: 'bra' },
      { nl: 'bij', en: 'at / with / near' },
      { nl: 'bitterbal', article: 'de', en: 'bitterball (Dutch meat snack)' },
      { nl: 'blauw', en: 'blue' },
      { nl: 'blik', article: 'het', en: 'tin / can' },
      { nl: 'blikje', article: 'het', en: 'small can' },
      { nl: 'bloem', article: 'de', en: 'flower / flour' },
      { nl: 'bloemenzaak', article: 'de', en: 'flower shop' },
      { nl: 'bloemkool', article: 'de', en: 'cauliflower' },
      { nl: 'blouse', article: 'de', en: 'blouse' },
      { nl: 'boek', article: 'het', en: 'book' },
      { nl: 'boekenkast', article: 'de', en: 'bookcase' },
      { nl: 'boekwinkel', article: 'de', en: 'bookshop' },
      { nl: 'bolletje', article: 'het', en: 'small ball / bread roll' },
      { nl: 'boodschap', article: 'de', en: 'errand / message' },
      { nl: 'boontje', article: 'het', en: 'little bean' },
      { nl: 'boormachine', article: 'de', en: 'drill (power tool)' },
      { nl: 'borrelhapjes', en: 'bar snacks (plural)' },
      { nl: 'boter', article: 'de', en: 'butter' },
      { nl: 'bouwmarkt', article: 'de', en: 'DIY store' },
      { nl: 'brengen', en: 'to bring' },
      { nl: 'brie', article: 'de', en: 'brie cheese' },
      { nl: 'brief', article: 'de', en: 'letter (mail)' },
      { nl: 'briefje', article: 'het', en: 'note / banknote' },
      { nl: 'broek', article: 'de', en: 'trousers / pants' },
      { nl: 'brood', article: 'het', en: 'bread' },
      { nl: 'broodje', article: 'het', en: 'bread roll / sandwich' },
      { nl: 'bruin', en: 'brown' },
      { nl: 'budget', article: 'het', en: 'budget' },
      { nl: 'bureau', article: 'het', en: 'desk / agency' },
      { nl: 'bus', article: 'de', en: 'bus / canister' },
      { nl: 'busje', article: 'het', en: 'small bus / small can' },
      { nl: 'café', article: 'het', en: 'café' },
      { nl: 'cake', article: 'de', en: 'cake' },
      { nl: 'cervelaat', article: 'de', en: 'cervelat sausage' },
      { nl: 'colbert', article: 'de/het', en: 'blazer / jacket' },
      { nl: 'contant', en: 'cash' },
      { nl: 'corrigeren', en: 'to correct' },
      { nl: 'croissant', article: 'de', en: 'croissant' },
      { nl: 'donker', en: 'dark' },
      { nl: 'donkerbruin', en: 'dark brown' },
      { nl: 'doos', article: 'de', en: 'box' },
      { nl: 'doosje', article: 'het', en: 'small box' },
      { nl: 'dorst', article: 'de', en: 'thirst' },
      { nl: 'douchecrème', article: 'de', en: 'shower gel' },
      { nl: 'dragen', en: 'to wear / carry' },
      { nl: 'dressoir', article: 'de/het', en: 'dresser / sideboard' },
      { nl: 'drinken', en: 'to drink' },
      { nl: 'drogist', article: 'de', en: 'druggist' },
      { nl: 'drogisterij', article: 'de', en: 'drugstore' },
      { nl: 'druif', article: 'de', en: 'grape' },
      { nl: 'duur', en: 'expensive' },
      { nl: 'eens', en: 'once / one day' },
      { nl: 'eettafel', article: 'de', en: 'dining table' },
      { nl: 'elkaar', en: 'each other' },
      { nl: 'er', en: 'there' },
      { nl: 'eten', en: 'to eat / food' },
      { nl: 'fauteuil', article: 'de', en: 'armchair' },
      { nl: 'fijn', en: 'nice / fine' },
      { nl: 'flat', article: 'de', en: 'flat / apartment' },
      { nl: 'fles', article: 'de', en: 'bottle' },
      { nl: 'flesje', article: 'het', en: 'small bottle' },
      { nl: 'framboos', article: 'de', en: 'raspberry' },
      { nl: 'gebak', article: 'het', en: 'pastry' },
      { nl: 'geel', en: 'yellow' },
      { nl: 'gehakt', article: 'het', en: 'minced meat' },
      { nl: 'gesneden', en: 'sliced / cut' },
      { nl: 'gezond', en: 'healthy' },
      { nl: 'goedkoop', en: 'cheap' },
      { nl: 'gram', article: 'het', en: 'gram' },
      { nl: 'grijs', en: 'grey' },
      { nl: 'groen', en: 'green' },
      { nl: 'groente', article: 'de', en: 'vegetable' },
      { nl: 'groenteman', article: 'de', en: 'greengrocer' },
      { nl: 'hak', article: 'de', en: 'heel (of shoe)' },
      { nl: 'half', en: 'half' },
      { nl: 'halsketting', article: 'de', en: 'necklace' },
      { nl: 'ham', article: 'de', en: 'ham' },
      { nl: 'hamburger', article: 'de', en: 'hamburger' },
      { nl: 'hamer', article: 'de', en: 'hammer' },
      { nl: 'handdoek', article: 'de', en: 'towel' },
      { nl: 'handschoen', article: 'de', en: 'glove' },
      { nl: 'hangen', en: 'to hang' },
      { nl: 'hartstikke', en: 'really / extremely' },
      { nl: 'heerlijk', en: 'delicious / lovely' },
      { nl: 'heet', en: 'hot' },
      { nl: 'helaas', en: 'unfortunately' },
      { nl: 'helpen', en: 'to help' },
      { nl: 'hem', en: 'him' },
      { nl: 'hen', en: 'them' },
      { nl: 'honger', en: 'hunger' },
      { nl: 'hoog', en: 'high' },
      { nl: 'hun', en: 'their / them' },
      { nl: 'inderdaad', en: 'indeed' },
      { nl: 'interessant', en: 'interesting' },
      { nl: 'jammer', en: 'too bad / pity' },
      { nl: 'jas', article: 'de', en: 'coat / jacket' },
      { nl: 'jenever', article: 'de', en: 'jenever (Dutch gin)' },
      { nl: 'jong', en: 'young' },
      { nl: 'jou', en: 'you (object, informal)' },
      { nl: 'jurk', article: 'de', en: 'dress' },
      { nl: 'juwelier', article: 'de', en: 'jeweler' },
      { nl: 'kaas', article: 'de', en: 'cheese' },
      { nl: 'kalender', article: 'de', en: 'calendar' },
      { nl: 'keeltablet', article: 'de', en: 'throat lozenge' },
      { nl: 'kers', article: 'de', en: 'cherry' },
      { nl: 'ketchup', article: 'de', en: 'ketchup' },
      { nl: 'keus', article: 'de', en: 'choice' },
      { nl: 'kijken', en: 'to look / watch' },
      { nl: 'kilo', article: 'de', en: 'kilo' },
      { nl: 'kip', article: 'de', en: 'chicken' },
      { nl: 'kipfilet', article: 'de', en: 'chicken fillet' },
      { nl: 'kippenbout', article: 'de', en: 'chicken leg' },
      { nl: 'kippenpoot', article: 'de', en: 'chicken leg / drumstick' },
      { nl: 'klant', article: 'de', en: 'customer' },
      { nl: 'kleding', article: 'de', en: 'clothing' },
      { nl: 'kledingwinkel', article: 'de', en: 'clothing store' },
      { nl: 'klein', en: 'small' },
      { nl: 'kleren', article: 'de', en: 'clothes' },
      { nl: 'kleur', article: 'de', en: 'colour' },
      { nl: 'koekje', article: 'het', en: 'cookie / biscuit' },
      { nl: 'koel', en: 'cool' },
      { nl: 'komkommer', article: 'de', en: 'cucumber' },
      { nl: 'koken', en: 'to cook' },
      { nl: 'koopavond', article: 'de', en: 'late shopping evening' },
      { nl: 'kort', en: 'short' },
      { nl: 'kosten', en: 'to cost' },
      { nl: 'kostuum', article: 'het', en: 'suit' },
      { nl: 'koud', en: 'cold' },
      { nl: 'krant', article: 'de', en: 'newspaper' },
      { nl: 'krentenbol', article: 'de', en: 'currant bun' },
      { nl: 'krop', article: 'de', en: 'head (of lettuce)' },
      { nl: 'kruk', article: 'de', en: 'stool' },
      { nl: 'laag', en: 'low' },
      { nl: 'laars', article: 'de', en: 'boot' },
      { nl: 'lamsvlees', article: 'het', en: 'lamb (meat)' },
      { nl: 'lang', en: 'long / tall' },
      { nl: 'lelijk', en: 'ugly' },
      { nl: 'lekker', en: 'tasty' },
      { nl: 'licht', en: 'light' },
      { nl: 'lichtbruin', en: 'light brown' },
      { nl: 'lijken', en: 'to seem / appear' },
      { nl: 'lippenstift', article: 'de', en: 'lipstick' },
      { nl: 'lopen', en: 'to walk' },
      { nl: 'maar', en: 'but' },
      { nl: 'maat', article: 'de', en: 'size' },
      { nl: 'make-up', article: 'de', en: 'make-up' },
      { nl: 'mandarijn', article: 'de', en: 'mandarin' },
      { nl: 'marktkraam', article: 'de', en: 'market stall' },
      { nl: 'melk', article: 'de', en: 'milk' },
      { nl: 'meloen', article: 'de', en: 'melon' },
      { nl: 'meneer', article: 'de', en: 'sir / mister' },
      { nl: 'menu', article: 'het', en: 'menu' },
      { nl: 'met', en: 'with' },
      { nl: 'mild', en: 'mild' },
      { nl: 'misschien', en: 'maybe' },
      { nl: 'model', article: 'het', en: 'model' },
      { nl: 'mooi', en: 'beautiful' },
      { nl: 'mouw', article: 'de', en: 'sleeve' },
      { nl: 'natuurlijk', en: 'of course / natural' },
      { nl: 'nemen', en: 'to take' },
      { nl: 'nog', en: 'still / yet' },
      { nl: 'ober', article: 'de', en: 'waiter' },
      { nl: 'ogenblik', article: 'het', en: 'moment' },
      { nl: 'oké', en: 'okay' },
      { nl: 'olie', article: 'de', en: 'oil' },
      { nl: 'onderbroek', article: 'de', en: 'underpants' },
      { nl: 'ondergoed', article: 'het', en: 'underwear' },
      { nl: 'ongeveer', en: 'approximately' },
      { nl: 'ongezond', en: 'unhealthy' },
      { nl: 'ons', en: 'us / 100 grams' },
      { nl: 'ook', en: 'also / too' },
      { nl: 'oorbel', article: 'de', en: 'earring' },
      { nl: 'oranje', en: 'orange' },
      { nl: 'overhemd', article: 'het', en: 'dress shirt' },
      { nl: 'overkant', article: 'de', en: 'other side' },
      { nl: 'paar', article: 'het', en: 'pair' },
      { nl: 'paars', en: 'purple' },
      { nl: 'pak', article: 'het', en: 'suit / pack' },
      { nl: 'pakje', article: 'het', en: 'small pack' },
      { nl: 'pantoffel', article: 'de', en: 'slipper' },
      { nl: 'papier', article: 'het', en: 'paper' },
      { nl: 'paprika', article: 'de', en: 'bell pepper' },
      { nl: 'passen', en: 'to fit / try on' },
      { nl: 'paté', article: 'de', en: 'pâté' },
      { nl: 'peer', article: 'de', en: 'pear' },
      { nl: 'pilsje', article: 'het', en: 'small beer (pils)' },
      { nl: 'pinautomaat', article: 'de', en: 'ATM' },
      { nl: 'pinnen', en: 'to pay by debit card' },
      { nl: 'pinpas', article: 'de', en: 'debit card' },
      { nl: 'pittig', en: 'spicy' },
      { nl: 'pizza', article: 'de', en: 'pizza' },
      { nl: 'plant', article: 'de', en: 'plant' },
      { nl: 'pleister', article: 'de', en: 'plaster / band-aid' },
      { nl: 'poloshirt', article: 'het', en: 'polo shirt' },
      { nl: 'pond', article: 'het', en: 'pound (500 grams)' },
      { nl: 'port', article: 'de', en: 'port (wine)' },
      { nl: 'portie', article: 'de', en: 'portion' },
      { nl: 'postuur', article: 'het', en: 'posture / build' },
      { nl: 'prei', article: 'de', en: 'leek' },
      { nl: 'prettig', en: 'pleasant' },
      { nl: 'prijs', article: 'de', en: 'price' },
      { nl: 'prima', en: 'fine / great' },
      { nl: 'printer', article: 'de', en: 'printer' },
      { nl: 'proberen', en: 'to try' },
      { nl: 'probleem', article: 'het', en: 'problem' },
      { nl: 'product', article: 'het', en: 'product' },
      { nl: 'pyjama', article: 'de', en: 'pyjamas' },
      { nl: 'reep', article: 'de', en: 'bar (chocolate)' },
      { nl: 'rekening', article: 'de', en: 'bill / account' },
      { nl: 'rijp', en: 'ripe' },
      { nl: 'ring', article: 'de', en: 'ring' },
      { nl: 'rok', article: 'de', en: 'skirt' },
      { nl: 'rol', article: 'de', en: 'roll' },
      { nl: 'rollade', article: 'de', en: 'roll roast' },
      { nl: 'rolletje', article: 'het', en: 'small roll' },
      { nl: 'rood', en: 'red' },
      { nl: 'roos', article: 'de', en: 'rose' },
      { nl: 'rosé', article: 'de', en: 'rosé wine' },
      { nl: 'roze', en: 'pink' },
      { nl: 'rundvlees', article: 'het', en: 'beef' },
      { nl: 'salami', article: 'de', en: 'salami' },
      { nl: 'samen', en: 'together' },
      { nl: 'sandaal', article: 'de', en: 'sandal' },
      { nl: 'sappig', en: 'juicy' },
      { nl: 'schoen', article: 'de', en: 'shoe' },
      { nl: 'schoenenzaak', article: 'de', en: 'shoe shop' },
      { nl: 'servies', article: 'het', en: 'dinnerware' },
      { nl: 'shampoo', article: 'de', en: 'shampoo' },
      { nl: 'shirt', article: 'het', en: 'shirt' },
      { nl: 'sinaasappel', article: 'de', en: 'orange (fruit)' },
      { nl: 'sjaal', article: 'de', en: 'scarf' },
      { nl: 'sla', article: 'de', en: 'lettuce / salad' },
      { nl: 'slager', article: 'de', en: 'butcher' },
      { nl: 'slagerij', article: 'de', en: "butcher's shop" },
      { nl: 'slagroom', article: 'de', en: 'whipped cream' },
      { nl: 'slipje', article: 'het', en: 'panties / briefs' },
      { nl: 'slipper', article: 'de', en: 'flip-flop' },
      { nl: 'smaken', en: 'to taste' },
      { nl: 'snijboon', article: 'de', en: 'string bean' },
      { nl: 'sok', article: 'de', en: 'sock' },
      { nl: 'sorry', en: 'sorry' },
      { nl: 'spaghetti', article: 'de', en: 'spaghetti' },
      { nl: 'speciaal', en: 'special' },
      { nl: 'spijkerbroek', article: 'de', en: 'jeans' },
      { nl: 'spinazie', article: 'de', en: 'spinach' },
      { nl: 'stem', article: 'de', en: 'voice / vote' },
      { nl: 'stil', en: 'quiet' },
      { nl: 'stoel', article: 'de', en: 'chair' },
      { nl: 'stokbrood', article: 'het', en: 'baguette' },
      { nl: 'stroopwafel', article: 'de', en: 'stroopwafel (syrup waffle)' },
      { nl: 'stropdas', article: 'de', en: 'tie (necktie)' },
      { nl: 'suiker', article: 'de', en: 'sugar' },
      { nl: 'supermarkt', article: 'de', en: 'supermarket' },
      { nl: 'taart', article: 'de', en: 'cake / pie' },
      { nl: 'tafel', article: 'de', en: 'table' },
      { nl: 'tas', article: 'de', en: 'bag' },
      { nl: 'tasje', article: 'het', en: 'small bag' },
      { nl: 'televisie', article: 'de', en: 'television' },
      { nl: 'terug', en: 'back' },
      { nl: 'tomaat', article: 'de', en: 'tomato' },
      { nl: 'trui', article: 'de', en: 'sweater / jumper' },
      { nl: 'T-shirt', article: 'het', en: 'T-shirt' },
      { nl: 'tulp', article: 'de', en: 'tulip' },
      { nl: 'ui', article: 'de', en: 'onion' },
      { nl: 'varkensvlees', article: 'het', en: 'pork' },
      { nl: 'veel', en: 'much / many' },
      { nl: 'verband', article: 'het', en: 'bandage' },
      { nl: 'verkoper', article: 'de', en: 'salesperson' },
      { nl: 'verrukkelijk', en: 'delightful / delicious' },
      { nl: 'vers', en: 'fresh' },
      { nl: 'verschillend', en: 'different / various' },
      { nl: 'vest', article: 'het', en: 'cardigan / vest' },
      { nl: 'vlaai', article: 'de', en: 'vlaai (Limburg fruit pie)' },
      { nl: 'vlees', article: 'het', en: 'meat' },
      { nl: 'vleeswaren', article: 'de', en: 'cold cuts (plural)' },
      { nl: 'voor', en: 'for / in front of' },
      { nl: 'warm', en: 'warm' },
      { nl: 'wat', en: 'what' },
      { nl: 'water', article: 'het', en: 'water' },
      { nl: 'wc-papier', article: 'het', en: 'toilet paper' },
      { nl: 'weekend', article: 'het', en: 'weekend' },
      { nl: 'weer', en: 'again / weather' },
      { nl: 'weinig', en: 'few / little' },
      { nl: 'whisky', article: 'de', en: 'whisky' },
      { nl: 'wijn', article: 'de', en: 'wine' },
      { nl: 'winkel', article: 'de', en: 'shop' },
      { nl: 'winkelen', en: 'to shop' },
      { nl: 'winter', article: 'de', en: 'winter' },
      { nl: 'wit', en: 'white' },
      { nl: 'worst', article: 'de', en: 'sausage' },
      { nl: 'zacht', en: 'soft' },
      { nl: 'zak', article: 'de', en: 'bag / pocket' },
      { nl: 'zakje', article: 'het', en: 'small bag' },
      { nl: 'ziens', en: 'see you (as in "tot ziens")' },
      { nl: 'zin', article: 'de', en: 'sentence / desire' },
      { nl: 'zoet', en: 'sweet' },
      { nl: 'zomer', article: 'de', en: 'summer' },
      { nl: 'zonder', en: 'without' },
      { nl: 'zout', en: 'salt / salty' },
      { nl: 'zuur', en: 'sour' },
      { nl: 'zwart', en: 'black' },
    ],
  },
  {
    id: 't4',
    name: 'Vervoer',
    label: 'Theme 4 · Vervoer (Transport)',
    cards: [
      { nl: 'aankomen', en: 'to arrive / gain weight' },
      { nl: 'aardig', en: 'nice / kind' },
      { nl: 'absoluut', en: 'absolutely' },
      { nl: 'accepteren', en: 'to accept' },
      { nl: 'als', en: 'if / when / as' },
      { nl: 'ander', en: 'other / another' },
      { nl: 'anders', en: 'different / otherwise' },
      { nl: 'balen', en: 'to be fed up' },
      { nl: 'bang', en: 'afraid / scared' },
      { nl: 'bedrijf', article: 'het', en: 'company' },
      { nl: 'beneden', en: 'downstairs / below' },
      { nl: 'bestemming', article: 'de', en: 'destination' },
      { nl: 'bezoek', article: 'het', en: 'visit' },
      { nl: 'bezoeken', en: 'to visit' },
      { nl: 'bijna', en: 'almost' },
      { nl: 'bijzonder', en: 'special / particular' },
      { nl: 'binnenkomen', en: 'to come in / enter' },
      { nl: 'binnenkort', en: 'soon' },
      { nl: 'binnenzak', article: 'de', en: 'inside pocket' },
      { nl: 'boot', article: 'de', en: 'boat' },
      { nl: 'boven', en: 'above / upstairs' },
      { nl: 'brug', article: 'de', en: 'bridge' },
      { nl: 'bus', article: 'de', en: 'bus' },
      { nl: 'bushalte', article: 'de', en: 'bus stop' },
      { nl: 'camping', article: 'de', en: 'campsite' },
      { nl: 'centrum', article: 'het', en: 'centre' },
      { nl: 'conducteur', article: 'de', en: 'train conductor' },
      { nl: 'coupé', article: 'de', en: 'compartment' },
      { nl: 'daar', en: 'there' },
      { nl: 'dame', article: 'de', en: 'lady' },
      { nl: 'deel', article: 'het', en: 'part' },
      { nl: 'dichtbij', en: 'nearby / close' },
      { nl: 'doel', article: 'het', en: 'goal / purpose' },
      { nl: 'dromen', en: 'to dream' },
      { nl: 'dubbeldekker', article: 'de', en: 'double-decker' },
      { nl: 'dun', en: 'thin' },
      { nl: 'duren', en: 'to last / take (time)' },
      { nl: 'eigen', en: 'own' },
      { nl: 'enkele reis', article: 'de', en: 'one-way ticket' },
      { nl: 'fantastisch', en: 'fantastic' },
      { nl: 'fiets', article: 'de', en: 'bicycle' },
      { nl: 'fietsen', en: 'to cycle' },
      { nl: 'file', article: 'de', en: 'traffic jam' },
      { nl: 'fluitje', article: 'het', en: 'whistle' },
      { nl: 'geduld', article: 'het', en: 'patience' },
      { nl: 'geloven', en: 'to believe' },
      { nl: 'genoeg', en: 'enough' },
      { nl: 'gesprek', article: 'het', en: 'conversation' },
      { nl: 'haast', article: 'de', en: 'hurry / haste' },
      { nl: 'heel', en: 'very / whole' },
      { nl: 'heer', article: 'de', en: 'gentleman / Mr' },
      { nl: 'helikopter', article: 'de', en: 'helicopter' },
      { nl: 'hier', en: 'here' },
      { nl: 'historisch', en: 'historic / historical' },
      { nl: 'hoofdstad', article: 'de', en: 'capital city' },
      { nl: 'huren', en: 'to rent' },
      { nl: 'iemand', en: 'someone' },
      { nl: 'in orde', en: 'okay / in order' },
      { nl: 'inchecken', en: 'to check in' },
      { nl: 'intercity', article: 'de', en: 'intercity train' },
      { nl: 'irriteren', en: 'to irritate' },
      { nl: 'jaloers', en: 'jealous' },
      { nl: 'kaartje', article: 'het', en: 'ticket' },
      { nl: 'kerk', article: 'de', en: 'church' },
      { nl: 'kijken', en: 'to look / watch' },
      { nl: 'kom op!', en: 'come on!' },
      { nl: 'korting', article: 'de', en: 'discount' },
      { nl: 'koud', en: 'cold' },
      { nl: 'kroeg', article: 'de', en: 'pub' },
      { nl: 'kwartier', article: 'het', en: 'quarter (of an hour)' },
      { nl: 'landen', en: 'to land' },
      { nl: 'langzaam', en: 'slow / slowly' },
      { nl: 'laten', en: 'to let / leave' },
      { nl: 'lied', article: 'het', en: 'song' },
      { nl: 'links', en: 'left' },
      { nl: 'lopen', en: 'to walk' },
      { nl: 'lopend', en: 'walking / on foot' },
      { nl: 'los', en: 'loose' },
      { nl: 'mailen', en: 'to email' },
      { nl: 'meestal', en: 'usually' },
      { nl: 'metro', article: 'de', en: 'metro / subway' },
      { nl: 'minister', article: 'de', en: 'minister (government)' },
      { nl: 'minuut', article: 'de', en: 'minute' },
      { nl: 'modern', en: 'modern' },
      { nl: 'motor(fiets)', article: 'de', en: 'motorcycle' },
      { nl: 'naar', en: 'to / towards' },
      { nl: 'negatief', en: 'negative' },
      { nl: 'nerveus', en: 'nervous' },
      { nl: 'nog', en: 'still / yet' },
      { nl: 'normaal', en: 'normal(ly)' },
      { nl: 'omdat', en: 'because' },
      { nl: 'omroeper', article: 'de', en: 'announcer' },
      { nl: 'onderweg', en: 'on the way' },
      { nl: 'op', en: 'on / up / finished' },
      { nl: 'openbaar', en: 'public' },
      { nl: 'ophalen', en: 'to pick up / collect' },
      { nl: 'oplossing', article: 'de', en: 'solution' },
      { nl: 'opschieten', en: 'to hurry up' },
      { nl: 'ov-chipkaart', article: 'de', en: 'public transport chip card' },
      { nl: 'over', en: 'over / about / past' },
      { nl: 'overstappen', en: 'to transfer / change (trains)' },
      { nl: 'pardon', en: 'pardon / excuse me' },
      { nl: 'passeren', en: 'to pass' },
      { nl: 'plaatsbewijs', article: 'het', en: 'travel ticket' },
      { nl: 'plan', article: 'het', en: 'plan' },
      { nl: 'plattegrond', article: 'de', en: 'street/city map' },
      { nl: 'plein', article: 'het', en: 'square (city)' },
      { nl: 'prachtig', en: 'magnificent / gorgeous' },
      { nl: 'prettig', en: 'pleasant' },
      { nl: 'procent', article: 'het', en: 'percent' },
      { nl: 'proef', article: 'de', en: 'test / experiment' },
      { nl: 'proeven', en: 'to taste' },
      { nl: 'radio', article: 'de', en: 'radio' },
      { nl: 'rechtdoor', en: 'straight ahead' },
      { nl: 'rechts', en: 'right' },
      { nl: 'reclame', article: 'de', en: 'advertisement' },
      { nl: 'reis', article: 'de', en: 'trip / journey' },
      { nl: 'reizen', en: 'to travel' },
      { nl: 'reiziger', article: 'de', en: 'traveller' },
      { nl: 'rennen', en: 'to run' },
      { nl: 'resultaat', article: 'het', en: 'result' },
      { nl: 'retour', article: 'het', en: 'return ticket' },
      { nl: 'rijden', en: 'to drive / ride' },
      { nl: 'rit', article: 'de', en: 'ride' },
      { nl: 'ring', article: 'de', en: 'ring (road)' },
      { nl: 'rivier', article: 'de', en: 'river' },
      { nl: 'roltrap', article: 'de', en: 'escalator' },
      { nl: 'rustig', en: 'quiet / calm' },
      { nl: 'saai', en: 'boring' },
      { nl: 'schip', article: 'het', en: 'ship' },
      { nl: 'schoon', en: 'clean' },
      { nl: 'scooter', article: 'de', en: 'scooter' },
      { nl: 'sluiten', en: 'to close' },
      { nl: 'smaken', en: 'to taste' },
      { nl: 'snelweg', article: 'de', en: 'motorway / highway' },
      { nl: 'spoor', article: 'het', en: 'track / platform' },
      { nl: 'spits', article: 'de', en: 'rush hour' },
      { nl: 'stappen', en: 'to step / go out' },
      { nl: 'station', article: 'het', en: 'station' },
      { nl: 'stilstaan', en: 'to stand still' },
      { nl: 'suggestie', article: 'de', en: 'suggestion' },
      { nl: 'taxi', article: 'de', en: 'taxi' },
      { nl: 'telefoon', article: 'de', en: 'phone' },
      { nl: 'terras', article: 'het', en: 'terrace' },
      { nl: 'te voet', en: 'on foot' },
      { nl: 'tijd', article: 'de', en: 'time' },
      { nl: 'tip', article: 'de', en: 'tip / advice' },
      { nl: 'toch', en: 'still / after all' },
      { nl: 'tocht', article: 'de', en: 'trip / draught' },
      { nl: 'totaal', en: 'total' },
      { nl: 'tram', article: 'de', en: 'tram' },
      { nl: 'trein', article: 'de', en: 'train' },
      { nl: 'uitchecken', en: 'to check out' },
      { nl: 'uur', article: 'het', en: 'hour' },
      { nl: 'vaak', en: 'often' },
      { nl: 'vallen', en: 'to fall' },
      { nl: 'van', en: 'from / of' },
      { nl: 'varen', en: 'to sail' },
      { nl: 'vast', en: 'fixed / probably' },
      { nl: 'veranderen', en: 'to change' },
      { nl: 'vertraagd', en: 'delayed' },
      { nl: 'vertraging', article: 'de', en: 'delay' },
      { nl: 'vertrekken', en: 'to depart' },
      { nl: 'vervoer', article: 'het', en: 'transport' },
      { nl: 'vervoermiddel', article: 'het', en: 'means of transport' },
      { nl: 'vlakbij', en: 'very close / nearby' },
      { nl: 'vliegen', en: 'to fly' },
      { nl: 'vliegtuig', article: 'het', en: 'airplane' },
      { nl: 'vlucht', article: 'de', en: 'flight' },
      { nl: 'vol', en: 'full' },
      { nl: 'vroeg', en: 'early' },
      { nl: 'waaien', en: 'to blow (of wind)' },
      { nl: 'wachten', en: 'to wait' },
      { nl: 'want', en: 'because' },
      { nl: 'zeilboot', article: 'de', en: 'sailboat' },
      { nl: 'zeilen', en: 'to sail' },
      { nl: 'zelf', en: 'self' },
      { nl: 'zonder', en: 'without' },
      { nl: 'zuiden', article: 'het', en: 'south' },
      { nl: 'zwaar', en: 'heavy' },
    ],
  },
  {
    id: 't5',
    name: 'Vrije tijd',
    label: "Theme 5 · Vrije tijd, uitgaan en hobby's (Leisure)",
    cards: [
      { nl: 'aanstaand', en: 'upcoming / next' },
      { nl: 'actief', en: 'active' },
      { nl: 'actueel', en: 'current / topical' },
      { nl: 'afdeling', article: 'de', en: 'department' },
      { nl: 'afwas', article: 'de', en: 'dishes to wash' },
      { nl: 'af en toe', en: 'now and then' },
      { nl: 'afgelopen', en: 'past / last' },
      { nl: 'alleen', en: 'alone / only' },
      { nl: 'altijd', en: 'always' },
      { nl: 'appartement', article: 'het', en: 'apartment' },
      { nl: 'arts', article: 'de', en: 'doctor' },
      { nl: 'ballet', article: 'het', en: 'ballet' },
      { nl: 'basketballen', en: 'to play basketball' },
      { nl: 'bellen', en: 'to call (on the phone)' },
      { nl: 'beroemd', en: 'famous' },
      { nl: 'beter', en: 'better' },
      { nl: 'best', en: 'best' },
      { nl: 'bezet', en: 'occupied / busy' },
      { nl: 'bioscoop', article: 'de', en: 'cinema' },
      { nl: 'boterham', article: 'de', en: 'sandwich (slice of bread)' },
      { nl: 'buur', article: 'de', en: 'neighbour' },
      { nl: 'buurt', article: 'de', en: 'neighbourhood' },
      { nl: 'calorie', article: 'de', en: 'calorie' },
      { nl: 'college', article: 'het', en: 'lecture / university class' },
      { nl: 'concert', article: 'het', en: 'concert' },
      { nl: 'daarna', en: 'afterwards' },
      { nl: 'dalen', en: 'to decrease / descend' },
      { nl: 'dan', en: 'then / than' },
      { nl: 'dansvoorstelling', article: 'de', en: 'dance performance' },
      { nl: 'dik', en: 'thick / fat' },
      { nl: 'douchen', en: 'to shower' },
      { nl: 'druk', en: 'busy' },
      { nl: 'echt', en: 'real(ly)' },
      { nl: 'eerst', en: 'first' },
      { nl: 'eigenlijk', en: 'actually' },
      { nl: 'energie', article: 'de', en: 'energy' },
      { nl: 'ervaren', en: 'to experience / experienced' },
      { nl: 'fan', article: 'de', en: 'fan' },
      { nl: 'favoriet', en: 'favourite' },
      { nl: 'fietsen', en: 'to cycle' },
      { nl: 'film', article: 'de', en: 'film' },
      { nl: 'flink', en: 'quite / sturdy' },
      { nl: 'gamen', en: 'to game' },
      { nl: 'gast', article: 'de', en: 'guest' },
      { nl: 'gebeuren', en: 'to happen' },
      { nl: 'geleden', en: 'ago' },
      { nl: 'genoeg', en: 'enough' },
      { nl: 'gitaar', article: 'de', en: 'guitar' },
      { nl: 'gratis', en: 'free (no cost)' },
      { nl: 'hekel', article: 'de', en: 'dislike (hekel hebben aan = to hate)' },
      { nl: 'helaas', en: 'unfortunately' },
      { nl: 'herhalen', en: 'to repeat' },
      { nl: 'hobby', article: 'de', en: 'hobby' },
      { nl: 'hockeyen', en: 'to play hockey' },
      { nl: 'horen', en: 'to hear' },
      { nl: 'hotel', article: 'het', en: 'hotel' },
      { nl: 'houden van', en: 'to love / like' },
      { nl: 'in', en: 'in' },
      { nl: 'inhoud', article: 'de', en: 'content' },
      { nl: 'instrument', article: 'het', en: 'instrument' },
      { nl: 'intellectueel', en: 'intellectual' },
      { nl: 'internet', article: 'het', en: 'internet' },
      { nl: 'jazz', article: 'de', en: 'jazz' },
      { nl: 'journaal', article: 'het', en: 'TV news' },
      { nl: 'kampioen', article: 'de', en: 'champion' },
      { nl: 'kantine', article: 'de', en: 'canteen' },
      { nl: 'keer', article: 'de', en: 'time (occasion)' },
      { nl: 'klassiek', en: 'classic / classical' },
      { nl: 'kletsen', en: 'to chat / chitchat' },
      { nl: 'komend', en: 'coming' },
      { nl: 'komisch', en: 'comical / funny' },
      { nl: 'koor', article: 'het', en: 'choir' },
      { nl: 'kop', article: 'de', en: 'cup / head' },
      { nl: 'kroeg', article: 'de', en: 'pub' },
      { nl: 'kroket', article: 'de', en: 'croquette' },
      { nl: 'kwart', article: 'het', en: 'quarter' },
      { nl: 'kwijtraken', en: 'to lose (something)' },
      { nl: 'laatste', en: 'last' },
      { nl: 'liefst', en: 'preferably' },
      { nl: 'liever', en: 'rather' },
      { nl: 'lijn', article: 'de', en: 'line' },
      { nl: 'makkelijk', en: 'easy' },
      { nl: 'meer', en: 'more' },
      { nl: 'meest', en: 'most' },
      { nl: 'meestal', en: 'usually' },
      { nl: 'middelbaar', en: 'middle / secondary' },
      { nl: 'middernacht', article: 'de', en: 'midnight' },
      { nl: 'minder', en: 'less' },
      { nl: 'minst', en: 'least' },
      { nl: 'muzikaal', en: 'musical' },
      { nl: 'na', en: 'after' },
      { nl: 'natuurlijk', en: 'of course' },
      { nl: 'nieuws', article: 'het', en: 'news' },
      { nl: 'nooit', en: 'never' },
      { nl: 'notulen', article: 'de', en: 'minutes (of meeting)' },
      { nl: 'oefenen', en: 'to practice' },
      { nl: 'om', en: 'at (time)' },
      { nl: 'ontbijten', en: 'to have breakfast' },
      { nl: 'ooit', en: 'ever' },
      { nl: 'op', en: 'on / up' },
      { nl: 'operatie', article: 'de', en: 'operation' },
      { nl: 'orkest', article: 'het', en: 'orchestra' },
      { nl: 'over', en: 'about / over' },
      { nl: 'overwerken', en: 'to work overtime' },
      { nl: 'per', en: 'per' },
      { nl: 'piano', article: 'de', en: 'piano' },
      { nl: 'popmuziek', article: 'de', en: 'pop music' },
      { nl: 'post', article: 'de', en: 'mail' },
      { nl: 'recensie', article: 'de', en: 'review' },
      { nl: 'regelen', en: 'to arrange' },
      { nl: 'regelmatig', en: 'regular(ly)' },
      { nl: 'reserveren', en: 'to reserve' },
      { nl: 'rijk', en: 'rich' },
      { nl: 'salsa', article: 'de', en: 'salsa' },
      { nl: 'schaatsen', en: 'to skate' },
      { nl: 'schilderen', en: 'to paint' },
      { nl: 'slagen', en: 'to succeed / pass' },
      { nl: 'slapen', en: 'to sleep' },
      { nl: 'snob', article: 'de', en: 'snob' },
      { nl: 'soms', en: 'sometimes' },
      { nl: 'spelen', en: 'to play' },
      { nl: 'speler', article: 'de', en: 'player' },
      { nl: 'sporten', en: 'to do sports' },
      { nl: 'sportief', en: 'sporty' },
      { nl: 'squashen', en: 'to play squash' },
      { nl: 'stijgen', en: 'to rise / climb' },
      { nl: 'stoppen', en: 'to stop' },
      { nl: 'studententijd', article: 'de', en: 'student years' },
      { nl: 'tabel', article: 'de', en: 'table (data)' },
      { nl: 'te', en: 'too / to' },
      { nl: 'team', article: 'het', en: 'team' },
      { nl: 'temperatuur', article: 'de', en: 'temperature' },
      { nl: 'ten slotte', en: 'finally' },
      { nl: 'tennissen', en: 'to play tennis' },
      { nl: 'theater', article: 'het', en: 'theatre' },
      { nl: 'toneel', article: 'het', en: 'stage / drama' },
      { nl: 'tot', en: 'until' },
      { nl: 'tot slot', en: 'to conclude' },
      { nl: 'tussen', en: 'between' },
      { nl: 'uitkijken', en: 'to watch out' },
      { nl: 'vaak', en: 'often' },
      { nl: 'van', en: 'from / of' },
      { nl: 'ver', en: 'far' },
      { nl: 'veranderen', en: 'to change' },
      { nl: 'verbeteren', en: 'to improve' },
      { nl: 'verder', en: 'further' },
      { nl: 'verdienen', en: 'to earn' },
      { nl: 'verhaal', article: 'het', en: 'story' },
      { nl: 'verliezen', en: 'to lose' },
      { nl: 'vermoeiend', en: 'tiring' },
      { nl: 'vertellen', en: 'to tell' },
      { nl: 'vervolgens', en: 'then / next' },
      { nl: 'viool', article: 'de', en: 'violin' },
      { nl: 'voetballen', en: 'to play football' },
      { nl: 'voetbalwedstrijd', article: 'de', en: 'football match' },
      { nl: 'volgen', en: 'to follow' },
      { nl: 'volgend', en: 'next' },
      { nl: 'volleyballen', en: 'to play volleyball' },
      { nl: 'voor', en: 'for' },
      { nl: 'vorig', en: 'previous' },
      { nl: 'vrij', en: 'free' },
      { nl: 'vroeger', en: 'earlier / formerly' },
      { nl: 'wakker', en: 'awake' },
      { nl: 'wandelen', en: 'to walk / hike' },
      { nl: 'wel', en: 'indeed / well' },
      { nl: 'wel eens', en: 'sometimes / once' },
      { nl: 'wereldrecord', article: 'het', en: 'world record' },
      { nl: 'werkdag', article: 'de', en: 'workday' },
      { nl: 'wijs', en: 'wise' },
      { nl: 'winnen', en: 'to win' },
      { nl: 'worden', en: 'to become' },
      { nl: 'zaal', article: 'de', en: 'hall / room' },
      { nl: 'zakken', en: 'to fail / drop' },
      { nl: 'zeker', en: 'certainly / sure' },
      { nl: 'zelden', en: 'rarely' },
      { nl: 'ziekenhuis', article: 'het', en: 'hospital' },
      { nl: 'zingen', en: 'to sing' },
      { nl: 'zojuist', en: 'just (now)' },
    ],
  },
  {
    id: 't6',
    name: 'Wonen',
    label: 'Theme 6 · Wonen (Housing)',
    cards: [
      { nl: 'aan', en: 'on / to' },
      { nl: 'aanbieden', en: 'to offer' },
      { nl: 'aanbod', article: 'het', en: 'offer / supply' },
      { nl: 'aandacht', article: 'de', en: 'attention' },
      { nl: 'aannemer', article: 'de', en: 'contractor' },
      { nl: 'aanrecht', article: 'het', en: 'kitchen counter' },
      { nl: 'aanspreken', en: 'to address / appeal to' },
      { nl: 'aardig', en: 'nice / kind' },
      { nl: 'achter', en: 'behind' },
      { nl: 'advertentie', article: 'de', en: 'advertisement' },
      { nl: 'afstandsbediening', article: 'de', en: 'remote control' },
      { nl: 'afzuigkap', article: 'de', en: 'extractor hood' },
      { nl: 'alleenstaand', en: 'single (unmarried)' },
      { nl: 'als volgt', en: 'as follows' },
      { nl: 'archiefkast', article: 'de', en: 'filing cabinet' },
      { nl: 'bad', article: 'het', en: 'bath' },
      { nl: 'badkamer', article: 'de', en: 'bathroom' },
      { nl: 'badmat', article: 'de', en: 'bath mat' },
      { nl: 'balkon', article: 'het', en: 'balcony' },
      { nl: 'bank', article: 'de', en: 'sofa / bank' },
      { nl: 'basis', article: 'de', en: 'base / basis' },
      { nl: 'basisschool', article: 'de', en: 'primary school' },
      { nl: 'bed', article: 'het', en: 'bed' },
      { nl: 'bedoelen', en: 'to mean' },
      { nl: 'begane grond', article: 'de', en: 'ground floor' },
      { nl: 'behangen', en: 'to wallpaper' },
      { nl: 'behanger', article: 'de', en: 'wallpaper hanger' },
      { nl: 'bekeuring', article: 'de', en: 'fine / ticket' },
      { nl: 'bekijken', en: 'to look at / view' },
      { nl: 'belangrijk', en: 'important' },
      { nl: 'betegelen', en: 'to tile' },
      { nl: 'bezichtiging', article: 'de', en: 'viewing (of a house)' },
      { nl: 'bij', en: 'at / with / near' },
      { nl: 'boete', article: 'de', en: 'fine / penalty' },
      { nl: 'boom', article: 'de', en: 'tree' },
      { nl: 'boven', en: 'above / upstairs' },
      { nl: 'brochure', article: 'de', en: 'brochure' },
      { nl: 'buiten', en: 'outside' },
      { nl: 'bureau', article: 'het', en: 'desk / agency' },
      { nl: 'bureaulamp', article: 'de', en: 'desk lamp' },
      { nl: 'bureaustoel', article: 'de', en: 'office chair' },
      { nl: 'buren', article: 'de', en: 'neighbours' },
      { nl: 'categorie', article: 'de', en: 'category' },
      { nl: 'dak', article: 'het', en: 'roof' },
      { nl: 'dakterras', article: 'het', en: 'roof terrace' },
      { nl: 'dalen', en: 'to fall / decrease' },
      { nl: 'dapper', en: 'brave' },
      { nl: 'dat', en: 'that' },
      { nl: 'dekbed', article: 'het', en: 'duvet' },
      { nl: 'deze', en: 'this / these' },
      { nl: 'dicht', en: 'closed / dense' },
      { nl: 'die', en: 'that / those' },
      { nl: 'direct', en: 'immediate(ly)' },
      { nl: 'dit', en: 'this' },
      { nl: 'douche', article: 'de', en: 'shower' },
      { nl: 'douchegordijn', article: 'het', en: 'shower curtain' },
      { nl: 'duidelijk', en: 'clear' },
      { nl: 'eengezinswoning', article: 'de', en: 'single-family home' },
      { nl: 'eigenlijk', en: 'actually' },
      { nl: 'elektricien', article: 'de', en: 'electrician' },
      { nl: 'ertussen zitten', en: 'to be in between' },
      { nl: 'etage', article: 'de', en: 'floor / storey' },
      { nl: 'fauteuil', article: 'de', en: 'armchair' },
      { nl: 'fietspad', article: 'het', en: 'bicycle path' },
      { nl: 'flat', article: 'de', en: 'flat / apartment' },
      { nl: 'fornuis', article: 'het', en: 'cooker / stove' },
      { nl: 'gang', article: 'de', en: 'hallway / corridor' },
      { nl: 'garage', article: 'de', en: 'garage' },
      { nl: 'geluidsoverlast', article: 'de', en: 'noise nuisance' },
      { nl: 'genoeg', en: 'enough' },
      { nl: 'gootsteen', article: 'de', en: 'sink' },
      { nl: 'gordijn', article: 'het', en: 'curtain' },
      { nl: 'gunstig', en: 'favourable' },
      { nl: 'hal', article: 'de', en: 'hall / entryway' },
      { nl: 'hangen', en: 'to hang' },
      { nl: 'hoek', article: 'de', en: 'corner' },
      { nl: 'hoekwoning', article: 'de', en: 'corner house' },
      { nl: 'hond', article: 'de', en: 'dog' },
      { nl: 'hondenpoep', article: 'de', en: 'dog poop' },
      { nl: 'horen van', en: 'to hear about' },
      { nl: 'hovenier', article: 'de', en: 'gardener' },
      { nl: 'huidig', en: 'current' },
      { nl: 'huur', article: 'de', en: 'rent' },
      { nl: 'huurwoning', article: 'de', en: 'rental property' },
      { nl: 'hypotheek', article: 'de', en: 'mortgage' },
      { nl: 'ideaal', en: 'ideal' },
      { nl: 'idee', article: 'het', en: 'idea' },
      { nl: 'iets', en: 'something' },
      { nl: 'informatie', article: 'de', en: 'information' },
      { nl: 'inkomen', article: 'het', en: 'income' },
      { nl: 'isolatie', article: 'de', en: 'insulation' },
      { nl: 'isoleren', en: 'to insulate' },
      { nl: 'jongere', article: 'de', en: 'young person / youth' },
      { nl: 'kachel', article: 'de', en: 'heater / stove' },
      { nl: 'kantoor', article: 'het', en: 'office' },
      { nl: 'kast', article: 'de', en: 'cupboard / closet' },
      { nl: 'kelder', article: 'de', en: 'cellar / basement' },
      { nl: 'keuken', article: 'de', en: 'kitchen' },
      { nl: 'keus', article: 'de', en: 'choice' },
      { nl: 'kinderopvang', article: 'de', en: 'childcare' },
      { nl: 'kledingkast', article: 'de', en: 'wardrobe' },
      { nl: 'kleed', article: 'het', en: 'rug / cloth' },
      { nl: 'klus', article: 'de', en: 'chore / odd job' },
      { nl: 'klussen', en: 'to do DIY / odd jobs' },
      { nl: 'koelkast', article: 'de', en: 'refrigerator' },
      { nl: 'koopwoning', article: 'de', en: 'owner-occupied home' },
      { nl: 'kraan', article: 'de', en: 'tap / faucet' },
      { nl: 'krant', article: 'de', en: 'newspaper' },
      { nl: 'kredietcrisis', article: 'de', en: 'credit crisis' },
      { nl: 'kussen', article: 'het', en: 'pillow / cushion' },
      { nl: 'laminaat', article: 'het', en: 'laminate (flooring)' },
      { nl: 'lamp', article: 'de', en: 'lamp' },
      { nl: 'laptop', article: 'de', en: 'laptop' },
      { nl: 'lawaai', article: 'het', en: 'noise / racket' },
      { nl: 'leggen', en: 'to lay / put down' },
      { nl: 'lekken', en: 'to leak' },
      { nl: 'lente', article: 'de', en: 'spring (season)' },
      { nl: 'licht', article: 'het', en: 'light' },
      { nl: 'lichtknop', article: 'de', en: 'light switch' },
      { nl: 'liggen aan', en: 'to depend on / be due to' },
      { nl: 'loodgieter', article: 'de', en: 'plumber' },
      { nl: 'magnetron', article: 'de', en: 'microwave' },
      { nl: 'makelaar', article: 'de', en: 'real estate agent' },
      { nl: 'makelaarskantoor', article: 'het', en: 'real estate agency' },
      { nl: 'maximaal', en: 'maximum / at most' },
      { nl: 'melden', en: 'to report / notify' },
      { nl: 'metselaar', article: 'de', en: 'bricklayer' },
      { nl: 'meubel', article: 'het', en: 'piece of furniture' },
      { nl: 'muur', article: 'de', en: 'wall' },
      { nl: 'naast', en: 'next to' },
      { nl: 'nachtkastje', article: 'het', en: 'bedside table' },
      { nl: 'nodig hebben', en: 'to need' },
      { nl: 'noorden', article: 'het', en: 'north' },
      { nl: 'om', en: 'around / at (time)' },
      { nl: 'omgeving', article: 'de', en: 'surroundings / area' },
      { nl: 'onder', en: 'under' },
      { nl: 'onderhouden', en: 'to maintain' },
      { nl: 'ontdekken', en: 'to discover' },
      { nl: 'opgroeien', en: 'to grow up' },
      { nl: 'ophangen', en: 'to hang up' },
      { nl: 'opnemen', en: 'to pick up (phone) / record' },
      { nl: 'opruimen', en: 'to tidy up' },
      { nl: 'oven', article: 'de', en: 'oven' },
      { nl: 'overkant', article: 'de', en: 'other side' },
      { nl: 'overlast', article: 'de', en: 'nuisance' },
      { nl: 'park', article: 'het', en: 'park' },
      { nl: 'parkeerplaats', article: 'de', en: 'parking spot' },
      { nl: 'parket', article: 'het', en: 'parquet flooring' },
      { nl: 'pensioen', article: 'het', en: 'pension' },
      { nl: 'plafond', article: 'het', en: 'ceiling' },
      { nl: 'poep', article: 'de', en: 'poop' },
      { nl: 'poepen', en: 'to poop' },
      { nl: 'prettig', en: 'pleasant' },
      { nl: 'prijscategorie', article: 'de', en: 'price category' },
      { nl: 'prijsklasse', article: 'de', en: 'price class' },
      { nl: 'printer', article: 'de', en: 'printer' },
      { nl: 'raamkozijn', article: 'het', en: 'window frame' },
      { nl: 'recent', en: 'recent' },
      { nl: 'relatief', en: 'relative(ly)' },
      { nl: 'repareren', en: 'to repair' },
      { nl: 'rond', en: 'around / round' },
      { nl: 'renovatie', article: 'de', en: 'renovation' },
      { nl: 'ruim', en: 'spacious' },
      { nl: 'rijtjeshuis', article: 'het', en: 'terraced house' },
      { nl: 'rustig', en: 'quiet / calm' },
      { nl: 'salontafel', article: 'de', en: 'coffee table' },
      { nl: 'samenwonen', en: 'to live together' },
      { nl: 'schemerlamp', article: 'de', en: 'floor lamp' },
      { nl: 'schijnen', en: 'to shine' },
      { nl: 'schilder', article: 'de', en: 'painter' },
      { nl: 'schilderen', en: 'to paint' },
      { nl: 'schilderij', article: 'het', en: 'painting' },
      { nl: 'schoorsteen', article: 'de', en: 'chimney' },
      { nl: 'schuur', article: 'de', en: 'shed' },
      { nl: 'seizoen', article: 'het', en: 'season' },
      { nl: 'seniorenwoning', article: 'de', en: 'senior housing' },
      { nl: 'sfeer', article: 'de', en: 'atmosphere / mood' },
      { nl: 'sinds', en: 'since' },
      { nl: 'situatie', article: 'de', en: 'situation' },
      { nl: 'slaapkamer', article: 'de', en: 'bedroom' },
      { nl: 'slot', article: 'het', en: 'lock / end' },
      { nl: 'spiegel', article: 'de', en: 'mirror' },
      { nl: 'spullen', article: 'de', en: 'stuff / things' },
      { nl: 'starter', article: 'de', en: 'first-time buyer' },
      { nl: 'stijl', article: 'de', en: 'style' },
      { nl: 'stoel', article: 'de', en: 'chair' },
      { nl: 'studeerkamer', article: 'de', en: 'study room' },
      { nl: 'tablet', article: 'de', en: 'tablet / iPad' },
      { nl: 'tafel', article: 'de', en: 'table' },
      { nl: 'tafeltje', article: 'het', en: 'little table' },
      { nl: 'tapijt', article: 'het', en: 'carpet' },
      { nl: 'tapijtlegger', article: 'de', en: 'carpet layer' },
      { nl: 'tegelzetter', article: 'de', en: 'tiler' },
      { nl: 'televisie', article: 'de', en: 'television' },
      { nl: 'tegen', en: 'against' },
      { nl: 'tegenover', en: 'opposite (of)' },
      { nl: 'tevreden', en: 'satisfied' },
      { nl: 'tijdschrift', article: 'het', en: 'magazine' },
      { nl: 'timmerman', article: 'de', en: 'carpenter' },
      { nl: 'toilet', article: 'het', en: 'toilet' },
      { nl: 'totaal', en: 'total' },
      { nl: 'trap', article: 'de', en: 'stairs' },
      { nl: 'tuin', article: 'de', en: 'garden' },
      { nl: 'tuinieren', en: 'to garden' },
      { nl: 'tussen', en: 'between' },
      { nl: 'tussenwoning', article: 'de', en: 'mid-terraced house' },
      { nl: 'twee-onder-een-kap-woning', article: 'de', en: 'semi-detached house' },
      { nl: 'tweepersoonsbed', article: 'het', en: 'double bed' },
      { nl: 'uitmaken', en: 'to matter / break up / put out' },
      { nl: 'uitlaten', en: 'to walk (the dog) / let out' },
      { nl: 'vaas', article: 'de', en: 'vase' },
      { nl: 'vaatwasser', article: 'de', en: 'dishwasher' },
      { nl: 'veilig', en: 'safe' },
      { nl: 'verdieping', article: 'de', en: 'floor / storey' },
      { nl: 'verhuizen', en: 'to move (house)' },
      { nl: 'verkeersoverlast', article: 'de', en: 'traffic nuisance' },
      { nl: 'verkopen', en: 'to sell' },
      { nl: 'verstoppen', en: 'to hide' },
      { nl: 'vervangen', en: 'to replace' },
      { nl: 'verwarming', article: 'de', en: 'heating' },
      { nl: 'verzamelen', en: 'to collect' },
      { nl: 'vitrage', article: 'de', en: 'net curtains' },
      { nl: 'vlag', article: 'de', en: 'flag' },
      { nl: 'voorstellen', en: 'to suggest / introduce' },
      { nl: 'voorwerp', article: 'het', en: 'object' },
      { nl: 'waarschijnlijk', en: 'probably' },
      { nl: 'wasmachine', article: 'de', en: 'washing machine' },
      { nl: 'wastafel', article: 'de', en: 'washbasin' },
      { nl: 'wc', article: 'de', en: 'toilet (WC)' },
      { nl: 'wekker', article: 'de', en: 'alarm clock' },
      { nl: 'werkkamer', article: 'de', en: 'workroom / home office' },
      { nl: 'wijk', article: 'de', en: 'neighbourhood' },
      { nl: 'witten', en: 'to whitewash' },
      { nl: 'woning', article: 'de', en: 'dwelling / house' },
      { nl: 'woningmarkt', article: 'de', en: 'housing market' },
      { nl: 'woonkamer', article: 'de', en: 'living room' },
      { nl: 'zoals', en: 'such as / like' },
      { nl: 'zolder', article: 'de', en: 'attic' },
      { nl: 'zon', article: 'de', en: 'sun' },
      { nl: 'zwanger', en: 'pregnant' },
    ],
  },
  {
    id: 't7',
    name: 'Gezondheidszorg',
    label: 'Theme 7 · Gezondheid(s)zorg (Health care)',
    cards: [
      { nl: 'aanbrengen', en: 'to apply (e.g. ointment)' },
      { nl: 'aanhouden', en: 'to keep on / pull over' },
      { nl: 'aankomen', en: 'to arrive / gain weight' },
      { nl: 'aantal', article: 'het', en: 'number / quantity' },
      { nl: 'aantrekken', en: 'to put on (clothes)' },
      { nl: 'aanwijzen', en: 'to point out' },
      { nl: 'aanzetten', en: 'to turn on' },
      { nl: 'aardappel', article: 'de', en: 'potato' },
      { nl: 'achterop', en: 'on the back' },
      { nl: 'advies', article: 'het', en: 'advice' },
      { nl: 'afdrogen', en: 'to dry off' },
      { nl: 'afmaken', en: 'to finish' },
      { nl: 'afspoelen', en: 'to rinse off' },
      { nl: 'afwassen', en: 'to wash up / do dishes' },
      { nl: 'allergie', article: 'de', en: 'allergy' },
      { nl: 'allergisch', en: 'allergic' },
      { nl: 'apotheek', article: 'de', en: 'pharmacy' },
      { nl: 'arm', article: 'de', en: 'arm' },
      { nl: 'assistente', article: 'de', en: 'assistant (female)' },
      { nl: 'bakken', en: 'to bake / fry' },
      { nl: 'been', article: 'het', en: 'leg / bone' },
      { nl: 'begin', article: 'het', en: 'beginning' },
      { nl: 'beweging', article: 'de', en: 'movement / motion' },
      { nl: 'bijsluiter', article: 'de', en: 'medication leaflet' },
      { nl: 'bijwerking', article: 'de', en: 'side effect' },
      { nl: 'bil', article: 'de', en: 'buttock' },
      { nl: 'binnen', en: 'inside' },
      { nl: 'blaas', article: 'de', en: 'bladder' },
      { nl: 'bloedvat', article: 'het', en: 'blood vessel' },
      { nl: 'borst', article: 'de', en: 'chest / breast' },
      { nl: 'borsten', article: 'de', en: 'breasts' },
      { nl: 'bovenbeen', article: 'het', en: 'thigh / upper leg' },
      { nl: 'braden', en: 'to roast' },
      { nl: 'breken', en: 'to break' },
      { nl: 'brood', article: 'het', en: 'bread' },
      { nl: 'buigen', en: 'to bend' },
      { nl: 'buik', article: 'de', en: 'belly / stomach' },
      { nl: 'capsule', article: 'de', en: 'capsule' },
      { nl: 'consult', article: 'het', en: 'consultation' },
      { nl: 'darm', article: 'de', en: 'intestine' },
      { nl: 'dichtdoen', en: 'to close' },
      { nl: 'dokter', article: 'de', en: 'doctor' },
      { nl: 'doordeweeks', en: 'on weekdays' },
      { nl: 'door … gaan', en: 'to sprain (e.g. ik ben door mijn enkel gegaan)' },
      { nl: 'door … heenlopen', en: 'to push through (e.g. pain)' },
      { nl: 'doorlezen', en: 'to read through' },
      { nl: 'doorlopen', en: 'to walk on / continue walking' },
      { nl: 'doorslikken', en: 'to swallow (down)' },
      { nl: 'doorverwijzen', en: 'to refer (to a specialist)' },
      { nl: 'draaien', en: 'to turn / rotate' },
      { nl: 'drank', article: 'de', en: 'drink / beverage / liquor' },
      { nl: 'drankje', article: 'het', en: 'little drink / liquid medicine' },
      { nl: 'droog', en: 'dry' },
      { nl: 'drukken', en: 'to press' },
      { nl: 'druppel', article: 'de', en: 'drop' },
      { nl: 'duim', article: 'de', en: 'thumb' },
      { nl: 'echt', en: 'real(ly)' },
      { nl: 'eerder', en: 'earlier' },
      { nl: 'ei', article: 'het', en: 'egg' },
      { nl: 'eigen', en: 'own' },
      { nl: 'elleboog', article: 'de', en: 'elbow' },
      { nl: 'enkel', article: 'de', en: 'ankle' },
      { nl: 'eventueel', en: 'possibly / if applicable' },
      { nl: 'frituren', en: 'to deep-fry' },
      { nl: 'fruit', article: 'het', en: 'fruit' },
      { nl: 'fysiotherapeut', article: 'de', en: 'physiotherapist' },
      { nl: 'fysiotherapie', article: 'de', en: 'physiotherapy' },
      { nl: 'gebeuren', en: 'to happen' },
      { nl: 'gebrek', article: 'het', en: 'lack / shortage' },
      { nl: 'gelden', en: 'to apply / be valid' },
      { nl: 'gemiddeld', en: 'average' },
      { nl: 'gewoon', en: 'normal / usual(ly)' },
      { nl: 'gezond', en: 'healthy' },
      { nl: 'gezondheid', article: 'de', en: 'health' },
      { nl: 'griep', article: 'de', en: 'flu' },
      { nl: 'groente', article: 'de', en: 'vegetable' },
      { nl: 'haar', article: 'het', en: 'hair' },
      { nl: 'hals', article: 'de', en: 'neck / throat' },
      { nl: 'halvarine', article: 'de', en: 'low-fat margarine' },
      { nl: 'hand', article: 'de', en: 'hand' },
      { nl: 'hart', article: 'het', en: 'heart' },
      { nl: 'heerlijk', en: 'delicious / lovely' },
      { nl: 'helemaal', en: 'entirely / completely' },
      { nl: 'herhaling', article: 'de', en: 'repeat / refill' },
      { nl: 'hersenen', article: 'de', en: 'brain(s)' },
      { nl: 'herstel', article: 'het', en: 'recovery' },
      { nl: 'heup', article: 'de', en: 'hip' },
      { nl: 'hiel', article: 'de', en: 'heel' },
      { nl: 'hinkelen', en: 'to hop (on one leg)' },
      { nl: 'hoeveelheid', article: 'de', en: 'quantity / amount' },
      { nl: 'hoofd', article: 'het', en: 'head' },
      { nl: 'hoofdpijn', article: 'de', en: 'headache' },
      { nl: 'hoofdstuk', article: 'het', en: 'chapter' },
      { nl: 'hopen', en: 'to hope' },
      { nl: 'horen', en: 'to hear' },
      { nl: 'houden', en: 'to hold / keep' },
      { nl: 'huisarts', article: 'de', en: 'general practitioner (GP)' },
      { nl: 'huisartsenpraktijk', article: 'de', en: 'GP practice' },
      { nl: 'huishouden', article: 'het', en: 'household' },
      { nl: 'inclusief', en: 'including' },
      { nl: 'inderdaad', en: 'indeed' },
      { nl: 'inleveren', en: 'to hand in' },
      { nl: 'innemen', en: 'to take (medicine)' },
      { nl: 'inschrijven (zich)', en: 'to register (oneself)' },
      { nl: 'instappen', en: 'to get in / board' },
      { nl: 'kaas', article: 'de', en: 'cheese' },
      { nl: 'karton', en: 'cardboard' },
      { nl: 'kauwen', en: 'to chew' },
      { nl: 'keel', article: 'de', en: 'throat' },
      { nl: 'keelpijn', article: 'de', en: 'sore throat' },
      { nl: 'kies', article: 'de', en: 'molar (tooth)' },
      { nl: 'kiezen', en: 'to choose' },
      { nl: 'kin', article: 'de', en: 'chin' },
      { nl: 'klaarmaken', en: 'to prepare' },
      { nl: 'kneuzen', en: 'to bruise' },
      { nl: 'knie', article: 'de', en: 'knee' },
      { nl: 'koelen', en: 'to cool' },
      { nl: 'koorts', article: 'de', en: 'fever' },
      { nl: 'kuit', article: 'de', en: 'calf (of leg)' },
      { nl: 'kut', article: 'de', en: 'pussy / cunt (vulgar)' },
      { nl: 'langs', en: 'along / past' },
      { nl: 'last', article: 'de', en: 'burden / trouble' },
      { nl: 'levensverwachting', article: 'de', en: 'life expectancy' },
      { nl: 'lever', article: 'de', en: 'liver' },
      { nl: 'lichaam', article: 'het', en: 'body' },
      { nl: 'linkerenkel', article: 'de', en: 'left ankle' },
      { nl: 'lip', article: 'de', en: 'lip' },
      { nl: 'long', article: 'de', en: 'lung' },
      { nl: 'luchtpijp', article: 'de', en: 'windpipe / trachea' },
      { nl: 'lul', article: 'de', en: 'dick (vulgar)' },
      { nl: 'maag', article: 'de', en: 'stomach' },
      { nl: 'manier', article: 'de', en: 'way / manner' },
      { nl: 'maximaal', en: 'maximum / at most' },
      { nl: 'mengen', en: 'to mix' },
      { nl: 'meteen', en: 'immediately' },
      { nl: 'middelvinger', article: 'de', en: 'middle finger' },
      { nl: 'minimaal', en: 'minimum / at least' },
      { nl: 'moe', en: 'tired' },
      { nl: 'mond', article: 'de', en: 'mouth' },
      { nl: 'navel', article: 'de', en: 'navel / belly button' },
      { nl: 'nek', article: 'de', en: 'back of the neck' },
      { nl: 'netvlies', article: 'het', en: 'retina' },
      { nl: 'neus', article: 'de', en: 'nose' },
      { nl: 'nier', article: 'de', en: 'kidney' },
      { nl: 'nog (nog niet)', en: 'still / yet (not yet)' },
      { nl: 'olie', article: 'de', en: 'oil' },
      { nl: 'omhouden', en: 'to keep on (e.g. coat)' },
      { nl: 'ongeveer', en: 'approximately' },
      { nl: 'ontzettend', en: 'terribly / very' },
      { nl: 'oog', article: 'het', en: 'eye' },
      { nl: 'oor', article: 'het', en: 'ear' },
      { nl: 'opbellen', en: 'to call up / phone' },
      { nl: 'opendoen', en: 'to open' },
      { nl: 'ophalen', en: 'to pick up / collect' },
      { nl: 'opnemen', en: 'to pick up (phone) / record' },
      { nl: 'opruimen', en: 'to tidy up' },
      { nl: 'opschrijven', en: 'to write down' },
      { nl: 'opstaan', en: 'to get up / stand up' },
      { nl: 'optreden', en: 'to perform / appear / occur' },
      { nl: 'opvallen', en: 'to stand out / be noticeable' },
      { nl: 'opzoeken', en: 'to look up / visit' },
      { nl: 'pas', en: 'just / only (recently)' },
      { nl: 'pasta', article: 'de', en: 'pasta / paste' },
      { nl: 'patiënt', article: 'de', en: 'patient' },
      { nl: 'penis', article: 'de', en: 'penis' },
      { nl: 'peulvrucht', article: 'de', en: 'legume' },
      { nl: 'pijn', article: 'de', en: 'pain' },
      { nl: 'pijnstiller', article: 'de', en: 'painkiller' },
      { nl: 'pil', article: 'de', en: 'pill' },
      { nl: 'pinda', article: 'de', en: 'peanut' },
      { nl: 'pink', article: 'de', en: 'little finger / pinky' },
      { nl: 'pols', article: 'de', en: 'wrist / pulse' },
      { nl: 'praktijk', article: 'de', en: 'practice (medical)' },
      { nl: 'radiator', article: 'de', en: 'radiator' },
      { nl: 'recept', article: 'het', en: 'prescription / recipe' },
      { nl: 'reden', article: 'de', en: 'reason' },
      { nl: 'rekverband', article: 'het', en: 'stretch bandage' },
      { nl: 'rijst', article: 'de', en: 'rice' },
      { nl: 'ringvinger', article: 'de', en: 'ring finger' },
      { nl: 'rug', article: 'de', en: 'back' },
      { nl: 'rust', article: 'de', en: 'rest / quiet' },
      { nl: 'samenwerken', en: 'to cooperate / work together' },
      { nl: 'schat', article: 'de', en: 'treasure / darling' },
      { nl: 'scheenbeen', article: 'het', en: 'shinbone' },
      { nl: 'schoonmaken', en: 'to clean' },
      { nl: 'schouder', article: 'de', en: 'shoulder' },
      { nl: 'scriptie', article: 'de', en: 'thesis' },
      { nl: 'slikken', en: 'to swallow' },
      { nl: 'slokdarm', article: 'de', en: 'oesophagus' },
      { nl: 'smeren', en: 'to spread / smear' },
      { nl: 'specialist', article: 'de', en: 'specialist' },
      { nl: 'spelen', en: 'to play' },
      { nl: 'spier', article: 'de', en: 'muscle' },
      { nl: 'spierpijn', article: 'de', en: 'muscle pain' },
      { nl: 'spray', article: 'de', en: 'spray' },
      { nl: 'spreekuur', article: 'het', en: 'office / consultation hours' },
      { nl: 'strekken', en: 'to stretch' },
      { nl: 'tablet', article: 'de/het', en: 'tablet' },
      { nl: 'tand', article: 'de', en: 'tooth' },
      { nl: 'tandarts', article: 'de', en: 'dentist' },
      { nl: 'teen', article: 'de', en: 'toe' },
      { nl: 'terecht', en: 'rightly / found / arrived' },
      { nl: 'terugbrengen', en: 'to bring back' },
      { nl: 'terugkomen', en: 'to come back' },
      { nl: 'toen', en: 'then / when (past)' },
      { nl: 'tong', article: 'de', en: 'tongue' },
      { nl: 'trekken', en: 'to pull' },
      { nl: 'trommelvlies', article: 'het', en: 'eardrum' },
      { nl: 'uitdoen', en: 'to take off / turn off' },
      { nl: 'uitgaan', en: 'to go out' },
      { nl: 'uitkijken', en: 'to watch out' },
      { nl: 'uitnodigen', en: 'to invite' },
      { nl: 'uitschrijven', en: 'to write out (e.g. a prescription)' },
      { nl: 'uitslapen', en: 'to sleep in' },
      { nl: 'uitstappen', en: 'to get off / out' },
      { nl: 'uitzetten', en: 'to turn off' },
      { nl: 'vagina', article: 'de', en: 'vagina' },
      { nl: 'van', en: 'from / of' },
      { nl: 'vensterbank', article: 'de', en: 'windowsill' },
      { nl: 'verband', article: 'het', en: 'bandage' },
      { nl: 'vergadering', article: 'de', en: 'meeting' },
      { nl: 'verkeerd', en: 'wrong' },
      { nl: 'verklaren', en: 'to explain / declare' },
      { nl: 'verkouden', en: 'having a cold' },
      { nl: 'vertellen', en: 'to tell' },
      { nl: 'verwijzing', article: 'de', en: 'referral' },
      { nl: 'vinger', article: 'de', en: 'finger' },
      { nl: 'vis', article: 'de', en: 'fish' },
      { nl: 'vlees', article: 'het', en: 'meat' },
      { nl: 'vleesvervanger', article: 'de', en: 'meat substitute' },
      { nl: 'voet', article: 'de', en: 'foot' },
      { nl: 'voorzichtig', en: 'careful' },
      { nl: 'wang', article: 'de', en: 'cheek' },
      { nl: 'wassen', en: 'to wash' },
      { nl: 'weggaan', en: 'to leave / go away' },
      { nl: 'wenkbrauw', article: 'de', en: 'eyebrow' },
      { nl: 'wereld', article: 'de', en: 'world' },
      { nl: 'weten', en: 'to know' },
      { nl: 'wijsvinger', article: 'de', en: 'index finger' },
      { nl: 'wimper', article: 'de', en: 'eyelash' },
      { nl: 'woonplaats', article: 'de', en: 'place of residence' },
      { nl: 'worden', en: 'to become' },
      { nl: 'zalf', article: 'de', en: 'ointment / salve' },
      { nl: 'zeggen', en: 'to say' },
      { nl: 'zelfstandig', en: 'independent' },
      { nl: 'ziek', en: 'sick / ill' },
      { nl: "zo'n", en: 'such a' },
    ],
  },
];

// Verb-conjugation and sentence-drill themes live alongside the vocabulary
// themes, in their own groups ('verbs', 'sentences').
THEMES.push(...VERB_THEMES, ...SENTENCE_THEMES);

// Build a stable id from theme + slug of nl; freeze for the runtime.
function slugify(s) {
  return s
    .toLowerCase()
    .replace(/['"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

for (const theme of THEMES) {
  theme.group = theme.group || 'vocab';
  for (const card of theme.cards) {
    card.id = `${theme.id}:${slugify(card.nl)}`;
  }
  Object.freeze(theme.cards);
}
Object.freeze(THEMES);

// Flat list across all themes (with the theme reference attached).
export const ALL_CARDS = THEMES.flatMap((t) =>
  t.cards.map((c) => ({ ...c, themeId: t.id, themeName: t.name }))
);

export function getThemeById(id) {
  return THEMES.find((t) => t.id === id) || null;
}

// Display name for each theme group, used to section the theme picker.
export const GROUP_LABELS = { vocab: 'Vocabulary', verbs: 'Verbs', sentences: 'Sentences' };
export const groupLabel = (g) => GROUP_LABELS[g] || 'Vocabulary';
