// Flashcard themes — sourced from "De Opmaat" (Beersmans & Tersteeg, 2020).
// Each card has a stable id derived from theme + Dutch slug so user progress
// survives edits to this file. Add new themes here.

export const THEMES = [
  {
    id: 't6',
    name: 'Wonen',
    label: 'Theme 6 · Wonen (Housing)',
    cards: [
      { nl: 'aan', en: 'on / to' },
      { nl: 'aanbieden', en: 'to offer' },
      { nl: 'aanbod', article: 'het', en: 'offer / supply' },
      { nl: 'aandacht', article: 'de', en: 'attention' },
      { nl: 'aannemer', article: 'de', en: 'contractor' },
      { nl: 'aanrecht', article: 'het', en: 'kitchen counter' },
      { nl: 'aanspreken', en: 'to address / appeal to' },
      { nl: 'aardig', en: 'nice / kind' },
      { nl: 'achter', en: 'behind' },
      { nl: 'advertentie', article: 'de', en: 'advertisement' },
      { nl: 'afstandsbediening', article: 'de', en: 'remote control' },
      { nl: 'afzuigkap', article: 'de', en: 'extractor hood' },
      { nl: 'alleenstaand', en: 'single (unmarried)' },
      { nl: 'als volgt', en: 'as follows' },
      { nl: 'archiefkast', article: 'de', en: 'filing cabinet' },
      { nl: 'bad', article: 'het', en: 'bath' },
      { nl: 'badkamer', article: 'de', en: 'bathroom' },
      { nl: 'badmat', article: 'de', en: 'bath mat' },
      { nl: 'balkon', article: 'het', en: 'balcony' },
      { nl: 'bank', article: 'de', en: 'sofa / bank' },
      { nl: 'basis', article: 'de', en: 'base / basis' },
      { nl: 'basisschool', article: 'de', en: 'primary school' },
      { nl: 'bed', article: 'het', en: 'bed' },
      { nl: 'bedoelen', en: 'to mean' },
      { nl: 'begane grond', article: 'de', en: 'ground floor' },
      { nl: 'behangen', en: 'to wallpaper' },
      { nl: 'behanger', article: 'de', en: 'wallpaper hanger' },
      { nl: 'bekeuring', article: 'de', en: 'fine / ticket' },
      { nl: 'bekijken', en: 'to look at / view' },
      { nl: 'belangrijk', en: 'important' },
      { nl: 'betegelen', en: 'to tile' },
      { nl: 'bezichtiging', article: 'de', en: 'viewing (of a house)' },
      { nl: 'bij', en: 'at / with / near' },
      { nl: 'boete', article: 'de', en: 'fine / penalty' },
      { nl: 'boom', article: 'de', en: 'tree' },
      { nl: 'boven', en: 'above / upstairs' },
      { nl: 'brochure', article: 'de', en: 'brochure' },
      { nl: 'buiten', en: 'outside' },
      { nl: 'bureau', article: 'het', en: 'desk / agency' },
      { nl: 'bureaulamp', article: 'de', en: 'desk lamp' },
      { nl: 'bureaustoel', article: 'de', en: 'office chair' },
      { nl: 'buren', article: 'de', en: 'neighbours' },
      { nl: 'categorie', article: 'de', en: 'category' },
      { nl: 'dak', article: 'het', en: 'roof' },
      { nl: 'dakterras', article: 'het', en: 'roof terrace' },
      { nl: 'dalen', en: 'to fall / decrease' },
      { nl: 'dapper', en: 'brave' },
      { nl: 'dat', en: 'that' },
      { nl: 'dekbed', article: 'het', en: 'duvet' },
      { nl: 'deze', en: 'this / these' },
      { nl: 'dicht', en: 'closed / dense' },
      { nl: 'die', en: 'that / those' },
      { nl: 'direct', en: 'immediate(ly)' },
      { nl: 'dit', en: 'this' },
      { nl: 'douche', article: 'de', en: 'shower' },
      { nl: 'douchegordijn', article: 'het', en: 'shower curtain' },
      { nl: 'duidelijk', en: 'clear' },
      { nl: 'eengezinswoning', article: 'de', en: 'single-family home' },
      { nl: 'eigenlijk', en: 'actually' },
      { nl: 'elektricien', article: 'de', en: 'electrician' },
      { nl: 'ertussen zitten', en: 'to be in between' },
      { nl: 'etage', article: 'de', en: 'floor / storey' },
      { nl: 'fauteuil', article: 'de', en: 'armchair' },
      { nl: 'fietspad', article: 'het', en: 'bicycle path' },
      { nl: 'flat', article: 'de', en: 'flat / apartment' },
      { nl: 'fornuis', article: 'het', en: 'cooker / stove' },
      { nl: 'gang', article: 'de', en: 'hallway / corridor' },
      { nl: 'garage', article: 'de', en: 'garage' },
      { nl: 'geluidsoverlast', article: 'de', en: 'noise nuisance' },
      { nl: 'genoeg', en: 'enough' },
      { nl: 'gootsteen', article: 'de', en: 'sink' },
      { nl: 'gordijn', article: 'het', en: 'curtain' },
      { nl: 'gunstig', en: 'favourable' },
      { nl: 'hal', article: 'de', en: 'hall / entryway' },
      { nl: 'hangen', en: 'to hang' },
      { nl: 'hoek', article: 'de', en: 'corner' },
      { nl: 'hoekwoning', article: 'de', en: 'corner house' },
      { nl: 'hond', article: 'de', en: 'dog' },
      { nl: 'hondenpoep', article: 'de', en: 'dog poop' },
      { nl: 'horen van', en: 'to hear about' },
      { nl: 'hovenier', article: 'de', en: 'gardener' },
      { nl: 'huidig', en: 'current' },
      { nl: 'huur', article: 'de', en: 'rent' },
      { nl: 'huurwoning', article: 'de', en: 'rental property' },
      { nl: 'hypotheek', article: 'de', en: 'mortgage' },
      { nl: 'ideaal', en: 'ideal' },
      { nl: 'idee', article: 'het', en: 'idea' },
      { nl: 'iets', en: 'something' },
      { nl: 'informatie', article: 'de', en: 'information' },
      { nl: 'inkomen', article: 'het', en: 'income' },
      { nl: 'isolatie', article: 'de', en: 'insulation' },
      { nl: 'isoleren', en: 'to insulate' },
      { nl: 'jongere', article: 'de', en: 'young person / youth' },
      { nl: 'kachel', article: 'de', en: 'heater / stove' },
      { nl: 'kantoor', article: 'het', en: 'office' },
      { nl: 'kast', article: 'de', en: 'cupboard / closet' },
      { nl: 'kelder', article: 'de', en: 'cellar / basement' },
      { nl: 'keuken', article: 'de', en: 'kitchen' },
      { nl: 'keus', article: 'de', en: 'choice' },
      { nl: 'kinderopvang', article: 'de', en: 'childcare' },
      { nl: 'kledingkast', article: 'de', en: 'wardrobe' },
      { nl: 'kleed', article: 'het', en: 'rug / cloth' },
      { nl: 'klus', article: 'de', en: 'chore / odd job' },
      { nl: 'klussen', en: 'to do DIY / odd jobs' },
      { nl: 'koelkast', article: 'de', en: 'refrigerator' },
      { nl: 'koopwoning', article: 'de', en: 'owner-occupied home' },
      { nl: 'kraan', article: 'de', en: 'tap / faucet' },
      { nl: 'krant', article: 'de', en: 'newspaper' },
      { nl: 'kredietcrisis', article: 'de', en: 'credit crisis' },
      { nl: 'kussen', article: 'het', en: 'pillow / cushion' },
      { nl: 'laminaat', article: 'het', en: 'laminate (flooring)' },
      { nl: 'lamp', article: 'de', en: 'lamp' },
      { nl: 'laptop', article: 'de', en: 'laptop' },
      { nl: 'lawaai', article: 'het', en: 'noise / racket' },
      { nl: 'leggen', en: 'to lay / put down' },
      { nl: 'lekken', en: 'to leak' },
      { nl: 'lente', article: 'de', en: 'spring (season)' },
      { nl: 'licht', article: 'het', en: 'light' },
      { nl: 'lichtknop', article: 'de', en: 'light switch' },
      { nl: 'liggen aan', en: 'to depend on / be due to' },
      { nl: 'loodgieter', article: 'de', en: 'plumber' },
      { nl: 'magnetron', article: 'de', en: 'microwave' },
      { nl: 'makelaar', article: 'de', en: 'real estate agent' },
      { nl: 'makelaarskantoor', article: 'het', en: 'real estate agency' },
      { nl: 'maximaal', en: 'maximum / at most' },
      { nl: 'melden', en: 'to report / notify' },
      { nl: 'metselaar', article: 'de', en: 'bricklayer' },
      { nl: 'meubel', article: 'het', en: 'piece of furniture' },
      { nl: 'muur', article: 'de', en: 'wall' },
      { nl: 'naast', en: 'next to' },
      { nl: 'nachtkastje', article: 'het', en: 'bedside table' },
      { nl: 'nodig hebben', en: 'to need' },
      { nl: 'noorden', article: 'het', en: 'north' },
      { nl: 'om', en: 'around / at (time)' },
      { nl: 'omgeving', article: 'de', en: 'surroundings / area' },
      { nl: 'onder', en: 'under' },
      { nl: 'onderhouden', en: 'to maintain' },
      { nl: 'ontdekken', en: 'to discover' },
      { nl: 'opgroeien', en: 'to grow up' },
      { nl: 'ophangen', en: 'to hang up' },
      { nl: 'opnemen', en: 'to pick up (phone) / record' },
      { nl: 'opruimen', en: 'to tidy up' },
      { nl: 'oven', article: 'de', en: 'oven' },
      { nl: 'overkant', article: 'de', en: 'other side' },
      { nl: 'overlast', article: 'de', en: 'nuisance' },
      { nl: 'park', article: 'het', en: 'park' },
      { nl: 'parkeerplaats', article: 'de', en: 'parking spot' },
      { nl: 'parket', article: 'het', en: 'parquet flooring' },
      { nl: 'pensioen', article: 'het', en: 'pension' },
      { nl: 'plafond', article: 'het', en: 'ceiling' },
      { nl: 'poep', article: 'de', en: 'poop' },
      { nl: 'poepen', en: 'to poop' },
      { nl: 'prettig', en: 'pleasant' },
      { nl: 'prijscategorie', article: 'de', en: 'price category' },
      { nl: 'prijsklasse', article: 'de', en: 'price class' },
      { nl: 'printer', article: 'de', en: 'printer' },
      { nl: 'raamkozijn', article: 'het', en: 'window frame' },
      { nl: 'recent', en: 'recent' },
      { nl: 'relatief', en: 'relative(ly)' },
      { nl: 'repareren', en: 'to repair' },
      { nl: 'rond', en: 'around / round' },
      { nl: 'renovatie', article: 'de', en: 'renovation' },
      { nl: 'ruim', en: 'spacious' },
      { nl: 'rijtjeshuis', article: 'het', en: 'terraced house' },
      { nl: 'rustig', en: 'quiet / calm' },
      { nl: 'salontafel', article: 'de', en: 'coffee table' },
      { nl: 'samenwonen', en: 'to live together' },
      { nl: 'schemerlamp', article: 'de', en: 'floor lamp' },
      { nl: 'schijnen', en: 'to shine' },
      { nl: 'schilder', article: 'de', en: 'painter' },
      { nl: 'schilderen', en: 'to paint' },
      { nl: 'schilderij', article: 'het', en: 'painting' },
      { nl: 'schoorsteen', article: 'de', en: 'chimney' },
      { nl: 'schuur', article: 'de', en: 'shed' },
      { nl: 'seizoen', article: 'het', en: 'season' },
      { nl: 'seniorenwoning', article: 'de', en: 'senior housing' },
      { nl: 'sfeer', article: 'de', en: 'atmosphere / mood' },
      { nl: 'sinds', en: 'since' },
      { nl: 'situatie', article: 'de', en: 'situation' },
      { nl: 'slaapkamer', article: 'de', en: 'bedroom' },
      { nl: 'slot', article: 'het', en: 'lock / end' },
      { nl: 'spiegel', article: 'de', en: 'mirror' },
      { nl: 'spullen', article: 'de', en: 'stuff / things' },
      { nl: 'starter', article: 'de', en: 'first-time buyer' },
      { nl: 'stijl', article: 'de', en: 'style' },
      { nl: 'stoel', article: 'de', en: 'chair' },
      { nl: 'studeerkamer', article: 'de', en: 'study room' },
      { nl: 'tablet', article: 'de', en: 'tablet / iPad' },
      { nl: 'tafel', article: 'de', en: 'table' },
      { nl: 'tafeltje', article: 'het', en: 'little table' },
      { nl: 'tapijt', article: 'het', en: 'carpet' },
      { nl: 'tapijtlegger', article: 'de', en: 'carpet layer' },
      { nl: 'tegelzetter', article: 'de', en: 'tiler' },
      { nl: 'televisie', article: 'de', en: 'television' },
      { nl: 'tegen', en: 'against' },
      { nl: 'tegenover', en: 'opposite (of)' },
      { nl: 'tevreden', en: 'satisfied' },
      { nl: 'tijdschrift', article: 'het', en: 'magazine' },
      { nl: 'timmerman', article: 'de', en: 'carpenter' },
      { nl: 'toilet', article: 'het', en: 'toilet' },
      { nl: 'totaal', en: 'total' },
      { nl: 'trap', article: 'de', en: 'stairs' },
      { nl: 'tuin', article: 'de', en: 'garden' },
      { nl: 'tuinieren', en: 'to garden' },
      { nl: 'tussen', en: 'between' },
      { nl: 'tussenwoning', article: 'de', en: 'mid-terraced house' },
      { nl: 'twee-onder-een-kap-woning', article: 'de', en: 'semi-detached house' },
      { nl: 'tweepersoonsbed', article: 'het', en: 'double bed' },
      { nl: 'uitmaken', en: 'to matter / break up / put out' },
      { nl: 'uitlaten', en: 'to walk (the dog) / let out' },
      { nl: 'vaas', article: 'de', en: 'vase' },
      { nl: 'vaatwasser', article: 'de', en: 'dishwasher' },
      { nl: 'veilig', en: 'safe' },
      { nl: 'verdieping', article: 'de', en: 'floor / storey' },
      { nl: 'verhuizen', en: 'to move (house)' },
      { nl: 'verkeersoverlast', article: 'de', en: 'traffic nuisance' },
      { nl: 'verkopen', en: 'to sell' },
      { nl: 'verstoppen', en: 'to hide' },
      { nl: 'vervangen', en: 'to replace' },
      { nl: 'verwarming', article: 'de', en: 'heating' },
      { nl: 'verzamelen', en: 'to collect' },
      { nl: 'vitrage', article: 'de', en: 'net curtains' },
      { nl: 'vlag', article: 'de', en: 'flag' },
      { nl: 'voorstellen', en: 'to suggest / introduce' },
      { nl: 'voorwerp', article: 'het', en: 'object' },
      { nl: 'waarschijnlijk', en: 'probably' },
      { nl: 'wasmachine', article: 'de', en: 'washing machine' },
      { nl: 'wastafel', article: 'de', en: 'washbasin' },
      { nl: 'wc', article: 'de', en: 'toilet (WC)' },
      { nl: 'wekker', article: 'de', en: 'alarm clock' },
      { nl: 'werkkamer', article: 'de', en: 'workroom / home office' },
      { nl: 'wijk', article: 'de', en: 'neighbourhood' },
      { nl: 'witten', en: 'to whitewash' },
      { nl: 'woning', article: 'de', en: 'dwelling / house' },
      { nl: 'woningmarkt', article: 'de', en: 'housing market' },
      { nl: 'woonkamer', article: 'de', en: 'living room' },
      { nl: 'zoals', en: 'such as / like' },
      { nl: 'zolder', article: 'de', en: 'attic' },
      { nl: 'zon', article: 'de', en: 'sun' },
      { nl: 'zwanger', en: 'pregnant' },
    ],
  },
  {
    id: 't7',
    name: 'Gezondheidszorg',
    label: 'Theme 7 · Gezondheid(s)zorg (Health care)',
    cards: [
      { nl: 'aanbrengen', en: 'to apply (e.g. ointment)' },
      { nl: 'aanhouden', en: 'to keep on / pull over' },
      { nl: 'aankomen', en: 'to arrive / gain weight' },
      { nl: 'aantal', article: 'het', en: 'number / quantity' },
      { nl: 'aantrekken', en: 'to put on (clothes)' },
      { nl: 'aanwijzen', en: 'to point out' },
      { nl: 'aanzetten', en: 'to turn on' },
      { nl: 'aardappel', article: 'de', en: 'potato' },
      { nl: 'achterop', en: 'on the back' },
      { nl: 'advies', article: 'het', en: 'advice' },
      { nl: 'afdrogen', en: 'to dry off' },
      { nl: 'afmaken', en: 'to finish' },
      { nl: 'afspoelen', en: 'to rinse off' },
      { nl: 'afwassen', en: 'to wash up / do dishes' },
      { nl: 'allergie', article: 'de', en: 'allergy' },
      { nl: 'allergisch', en: 'allergic' },
      { nl: 'apotheek', article: 'de', en: 'pharmacy' },
      { nl: 'arm', article: 'de', en: 'arm' },
      { nl: 'assistente', article: 'de', en: 'assistant (female)' },
      { nl: 'bakken', en: 'to bake / fry' },
      { nl: 'been', article: 'het', en: 'leg / bone' },
      { nl: 'begin', article: 'het', en: 'beginning' },
      { nl: 'beweging', article: 'de', en: 'movement / motion' },
      { nl: 'bijsluiter', article: 'de', en: 'medication leaflet' },
      { nl: 'bijwerking', article: 'de', en: 'side effect' },
      { nl: 'bil', article: 'de', en: 'buttock' },
      { nl: 'binnen', en: 'inside' },
      { nl: 'blaas', article: 'de', en: 'bladder' },
      { nl: 'bloedvat', article: 'het', en: 'blood vessel' },
      { nl: 'borst', article: 'de', en: 'chest / breast' },
      { nl: 'borsten', article: 'de', en: 'breasts' },
      { nl: 'bovenbeen', article: 'het', en: 'thigh / upper leg' },
      { nl: 'braden', en: 'to roast' },
      { nl: 'breken', en: 'to break' },
      { nl: 'brood', article: 'het', en: 'bread' },
      { nl: 'buigen', en: 'to bend' },
      { nl: 'buik', article: 'de', en: 'belly / stomach' },
      { nl: 'capsule', article: 'de', en: 'capsule' },
      { nl: 'consult', article: 'het', en: 'consultation' },
      { nl: 'darm', article: 'de', en: 'intestine' },
      { nl: 'dichtdoen', en: 'to close' },
      { nl: 'dokter', article: 'de', en: 'doctor' },
      { nl: 'doordeweeks', en: 'on weekdays' },
      { nl: 'door … gaan', en: 'to sprain (e.g. ik ben door mijn enkel gegaan)' },
      { nl: 'door … heenlopen', en: 'to push through (e.g. pain)' },
      { nl: 'doorlezen', en: 'to read through' },
      { nl: 'doorlopen', en: 'to walk on / continue walking' },
      { nl: 'doorslikken', en: 'to swallow (down)' },
      { nl: 'doorverwijzen', en: 'to refer (to a specialist)' },
      { nl: 'draaien', en: 'to turn / rotate' },
      { nl: 'drank', article: 'de', en: 'drink / beverage / liquor' },
      { nl: 'drankje', article: 'het', en: 'little drink / liquid medicine' },
      { nl: 'droog', en: 'dry' },
      { nl: 'drukken', en: 'to press' },
      { nl: 'druppel', article: 'de', en: 'drop' },
      { nl: 'duim', article: 'de', en: 'thumb' },
      { nl: 'echt', en: 'real(ly)' },
      { nl: 'eerder', en: 'earlier' },
      { nl: 'ei', article: 'het', en: 'egg' },
      { nl: 'eigen', en: 'own' },
      { nl: 'elleboog', article: 'de', en: 'elbow' },
      { nl: 'enkel', article: 'de', en: 'ankle' },
      { nl: 'eventueel', en: 'possibly / if applicable' },
      { nl: 'frituren', en: 'to deep-fry' },
      { nl: 'fruit', article: 'het', en: 'fruit' },
      { nl: 'fysiotherapeut', article: 'de', en: 'physiotherapist' },
      { nl: 'fysiotherapie', article: 'de', en: 'physiotherapy' },
      { nl: 'gebeuren', en: 'to happen' },
      { nl: 'gebrek', article: 'het', en: 'lack / shortage' },
      { nl: 'gelden', en: 'to apply / be valid' },
      { nl: 'gemiddeld', en: 'average' },
      { nl: 'gewoon', en: 'normal / usual(ly)' },
      { nl: 'gezond', en: 'healthy' },
      { nl: 'gezondheid', article: 'de', en: 'health' },
      { nl: 'griep', article: 'de', en: 'flu' },
      { nl: 'groente', article: 'de', en: 'vegetable' },
      { nl: 'haar', article: 'het', en: 'hair' },
      { nl: 'hals', article: 'de', en: 'neck / throat' },
      { nl: 'halvarine', article: 'de', en: 'low-fat margarine' },
      { nl: 'hand', article: 'de', en: 'hand' },
      { nl: 'hart', article: 'het', en: 'heart' },
      { nl: 'heerlijk', en: 'delicious / lovely' },
      { nl: 'helemaal', en: 'entirely / completely' },
      { nl: 'herhaling', article: 'de', en: 'repeat / refill' },
      { nl: 'hersenen', article: 'de', en: 'brain(s)' },
      { nl: 'herstel', article: 'het', en: 'recovery' },
      { nl: 'heup', article: 'de', en: 'hip' },
      { nl: 'hiel', article: 'de', en: 'heel' },
      { nl: 'hinkelen', en: 'to hop (on one leg)' },
      { nl: 'hoeveelheid', article: 'de', en: 'quantity / amount' },
      { nl: 'hoofd', article: 'het', en: 'head' },
      { nl: 'hoofdpijn', article: 'de', en: 'headache' },
      { nl: 'hoofdstuk', article: 'het', en: 'chapter' },
      { nl: 'hopen', en: 'to hope' },
      { nl: 'horen', en: 'to hear' },
      { nl: 'houden', en: 'to hold / keep' },
      { nl: 'huisarts', article: 'de', en: 'general practitioner (GP)' },
      { nl: 'huisartsenpraktijk', article: 'de', en: 'GP practice' },
      { nl: 'huishouden', article: 'het', en: 'household' },
      { nl: 'inclusief', en: 'including' },
      { nl: 'inderdaad', en: 'indeed' },
      { nl: 'inleveren', en: 'to hand in' },
      { nl: 'innemen', en: 'to take (medicine)' },
      { nl: 'inschrijven (zich)', en: 'to register (oneself)' },
      { nl: 'instappen', en: 'to get in / board' },
      { nl: 'kaas', article: 'de', en: 'cheese' },
      { nl: 'karton', en: 'cardboard' },
      { nl: 'kauwen', en: 'to chew' },
      { nl: 'keel', article: 'de', en: 'throat' },
      { nl: 'keelpijn', article: 'de', en: 'sore throat' },
      { nl: 'kies', article: 'de', en: 'molar (tooth)' },
      { nl: 'kiezen', en: 'to choose' },
      { nl: 'kin', article: 'de', en: 'chin' },
      { nl: 'klaarmaken', en: 'to prepare' },
      { nl: 'kneuzen', en: 'to bruise' },
      { nl: 'knie', article: 'de', en: 'knee' },
      { nl: 'koelen', en: 'to cool' },
      { nl: 'koorts', article: 'de', en: 'fever' },
      { nl: 'kuit', article: 'de', en: 'calf (of leg)' },
      { nl: 'kut', article: 'de', en: 'pussy / cunt (vulgar)' },
      { nl: 'langs', en: 'along / past' },
      { nl: 'last', article: 'de', en: 'burden / trouble' },
      { nl: 'levensverwachting', article: 'de', en: 'life expectancy' },
      { nl: 'lever', article: 'de', en: 'liver' },
      { nl: 'lichaam', article: 'het', en: 'body' },
      { nl: 'linkerenkel', article: 'de', en: 'left ankle' },
      { nl: 'lip', article: 'de', en: 'lip' },
      { nl: 'long', article: 'de', en: 'lung' },
      { nl: 'luchtpijp', article: 'de', en: 'windpipe / trachea' },
      { nl: 'lul', article: 'de', en: 'dick (vulgar)' },
      { nl: 'maag', article: 'de', en: 'stomach' },
      { nl: 'manier', article: 'de', en: 'way / manner' },
      { nl: 'maximaal', en: 'maximum / at most' },
      { nl: 'mengen', en: 'to mix' },
      { nl: 'meteen', en: 'immediately' },
      { nl: 'middelvinger', article: 'de', en: 'middle finger' },
      { nl: 'minimaal', en: 'minimum / at least' },
      { nl: 'moe', en: 'tired' },
      { nl: 'mond', article: 'de', en: 'mouth' },
      { nl: 'navel', article: 'de', en: 'navel / belly button' },
      { nl: 'nek', article: 'de', en: 'back of the neck' },
      { nl: 'netvlies', article: 'het', en: 'retina' },
      { nl: 'neus', article: 'de', en: 'nose' },
      { nl: 'nier', article: 'de', en: 'kidney' },
      { nl: 'nog (nog niet)', en: 'still / yet (not yet)' },
      { nl: 'olie', article: 'de', en: 'oil' },
      { nl: 'omhouden', en: 'to keep on (e.g. coat)' },
      { nl: 'ongeveer', en: 'approximately' },
      { nl: 'ontzettend', en: 'terribly / very' },
      { nl: 'oog', article: 'het', en: 'eye' },
      { nl: 'oor', article: 'het', en: 'ear' },
      { nl: 'opbellen', en: 'to call up / phone' },
      { nl: 'opendoen', en: 'to open' },
      { nl: 'ophalen', en: 'to pick up / collect' },
      { nl: 'opnemen', en: 'to pick up (phone) / record' },
      { nl: 'opruimen', en: 'to tidy up' },
      { nl: 'opschrijven', en: 'to write down' },
      { nl: 'opstaan', en: 'to get up / stand up' },
      { nl: 'optreden', en: 'to perform / appear / occur' },
      { nl: 'opvallen', en: 'to stand out / be noticeable' },
      { nl: 'opzoeken', en: 'to look up / visit' },
      { nl: 'pas', en: 'just / only (recently)' },
      { nl: 'pasta', article: 'de', en: 'pasta / paste' },
      { nl: 'patiënt', article: 'de', en: 'patient' },
      { nl: 'penis', article: 'de', en: 'penis' },
      { nl: 'peulvrucht', article: 'de', en: 'legume' },
      { nl: 'pijn', article: 'de', en: 'pain' },
      { nl: 'pijnstiller', article: 'de', en: 'painkiller' },
      { nl: 'pil', article: 'de', en: 'pill' },
      { nl: 'pinda', article: 'de', en: 'peanut' },
      { nl: 'pink', article: 'de', en: 'little finger / pinky' },
      { nl: 'pols', article: 'de', en: 'wrist / pulse' },
      { nl: 'praktijk', article: 'de', en: 'practice (medical)' },
      { nl: 'radiator', article: 'de', en: 'radiator' },
      { nl: 'recept', article: 'het', en: 'prescription / recipe' },
      { nl: 'reden', article: 'de', en: 'reason' },
      { nl: 'rekverband', article: 'het', en: 'stretch bandage' },
      { nl: 'rijst', article: 'de', en: 'rice' },
      { nl: 'ringvinger', article: 'de', en: 'ring finger' },
      { nl: 'rug', article: 'de', en: 'back' },
      { nl: 'rust', article: 'de', en: 'rest / quiet' },
      { nl: 'samenwerken', en: 'to cooperate / work together' },
      { nl: 'schat', article: 'de', en: 'treasure / darling' },
      { nl: 'scheenbeen', article: 'het', en: 'shinbone' },
      { nl: 'schoonmaken', en: 'to clean' },
      { nl: 'schouder', article: 'de', en: 'shoulder' },
      { nl: 'scriptie', article: 'de', en: 'thesis' },
      { nl: 'slikken', en: 'to swallow' },
      { nl: 'slokdarm', article: 'de', en: 'oesophagus' },
      { nl: 'smeren', en: 'to spread / smear' },
      { nl: 'specialist', article: 'de', en: 'specialist' },
      { nl: 'spelen', en: 'to play' },
      { nl: 'spier', article: 'de', en: 'muscle' },
      { nl: 'spierpijn', article: 'de', en: 'muscle pain' },
      { nl: 'spray', article: 'de', en: 'spray' },
      { nl: 'spreekuur', article: 'het', en: 'office / consultation hours' },
      { nl: 'strekken', en: 'to stretch' },
      { nl: 'tablet', article: 'de/het', en: 'tablet' },
      { nl: 'tand', article: 'de', en: 'tooth' },
      { nl: 'tandarts', article: 'de', en: 'dentist' },
      { nl: 'teen', article: 'de', en: 'toe' },
      { nl: 'terecht', en: 'rightly / found / arrived' },
      { nl: 'terugbrengen', en: 'to bring back' },
      { nl: 'terugkomen', en: 'to come back' },
      { nl: 'toen', en: 'then / when (past)' },
      { nl: 'tong', article: 'de', en: 'tongue' },
      { nl: 'trekken', en: 'to pull' },
      { nl: 'trommelvlies', article: 'het', en: 'eardrum' },
      { nl: 'uitdoen', en: 'to take off / turn off' },
      { nl: 'uitgaan', en: 'to go out' },
      { nl: 'uitkijken', en: 'to watch out' },
      { nl: 'uitnodigen', en: 'to invite' },
      { nl: 'uitschrijven', en: 'to write out (e.g. a prescription)' },
      { nl: 'uitslapen', en: 'to sleep in' },
      { nl: 'uitstappen', en: 'to get off / out' },
      { nl: 'uitzetten', en: 'to turn off' },
      { nl: 'vagina', article: 'de', en: 'vagina' },
      { nl: 'van', en: 'from / of' },
      { nl: 'vensterbank', article: 'de', en: 'windowsill' },
      { nl: 'verband', article: 'het', en: 'bandage' },
      { nl: 'vergadering', article: 'de', en: 'meeting' },
      { nl: 'verkeerd', en: 'wrong' },
      { nl: 'verklaren', en: 'to explain / declare' },
      { nl: 'verkouden', en: 'having a cold' },
      { nl: 'vertellen', en: 'to tell' },
      { nl: 'verwijzing', article: 'de', en: 'referral' },
      { nl: 'vinger', article: 'de', en: 'finger' },
      { nl: 'vis', article: 'de', en: 'fish' },
      { nl: 'vlees', article: 'het', en: 'meat' },
      { nl: 'vleesvervanger', article: 'de', en: 'meat substitute' },
      { nl: 'voet', article: 'de', en: 'foot' },
      { nl: 'voorzichtig', en: 'careful' },
      { nl: 'wang', article: 'de', en: 'cheek' },
      { nl: 'wassen', en: 'to wash' },
      { nl: 'weggaan', en: 'to leave / go away' },
      { nl: 'wenkbrauw', article: 'de', en: 'eyebrow' },
      { nl: 'wereld', article: 'de', en: 'world' },
      { nl: 'weten', en: 'to know' },
      { nl: 'wijsvinger', article: 'de', en: 'index finger' },
      { nl: 'wimper', article: 'de', en: 'eyelash' },
      { nl: 'woonplaats', article: 'de', en: 'place of residence' },
      { nl: 'worden', en: 'to become' },
      { nl: 'zalf', article: 'de', en: 'ointment / salve' },
      { nl: 'zeggen', en: 'to say' },
      { nl: 'zelfstandig', en: 'independent' },
      { nl: 'ziek', en: 'sick / ill' },
      { nl: "zo'n", en: 'such a' },
    ],
  },
];

// Build a stable id from theme + slug of nl; freeze for the runtime.
function slugify(s) {
  return s
    .toLowerCase()
    .replace(/['"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

for (const theme of THEMES) {
  for (const card of theme.cards) {
    card.id = `${theme.id}:${slugify(card.nl)}`;
  }
  Object.freeze(theme.cards);
}
Object.freeze(THEMES);

// Flat list across all themes (with the theme reference attached).
export const ALL_CARDS = THEMES.flatMap((t) =>
  t.cards.map((c) => ({ ...c, themeId: t.id, themeName: t.name }))
);

export function getThemeById(id) {
  return THEMES.find((t) => t.id === id) || null;
}
